import fs from 'node:fs';
import path from 'node:path';
import { ROOT, loadJson, writeJson, scanEntities, sha256, writeMarkdownEntity } from './common.mjs';
import { applications, applicationByCode } from './source-workspace.mjs';
import { scanSource, loadSourceIndex } from './source-intelligence.mjs';
import { createBaseline } from './change-history.mjs';

const RUNTIME = '.project-docs/brownfield';
const INVENTORY = `${RUNTIME}/inventory.json`;
const CANDIDATES = `${RUNTIME}/candidates.json`;
const RECONCILIATION = `${RUNTIME}/reconciliation.json`;
const REFACTOR_PLAN = `${RUNTIME}/refactor-plan.json`;

function cfg(){ return loadJson('registry/brownfield.json',{candidatePolicy:{},reconciliation:{},normalization:{},adapters:{}}); }
function norm(v){ return String(v||'').replaceAll('\\','/').replace(/^\.\//,'').replace(/\/$/,''); }
function inside(child,parent){ child=norm(child); parent=norm(parent); return child===parent || child.startsWith(parent+'/'); }
function slug(v){ return String(v||'').replace(/([a-z0-9])([A-Z])/g,'$1-$2').replace(/[^A-Za-z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase() || 'item'; }
function title(v){ return String(v||'item').replace(/([a-z0-9])([A-Z])/g,'$1 $2').replace(/[_\-.]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase()).trim(); }
function appToken(code){ return String(code||'APP').replace(/^APP[-_]?/i,'').replace(/[^A-Za-z0-9]+/g,'-').toUpperCase() || 'APP'; }
function candidateId(type,app,key){ return `CAND-${type.toUpperCase().replace(/[^A-Z0-9]+/g,'-')}-${sha256(`${app}|${type}|${key}`).slice(0,10).toUpperCase()}`; }
function codeFor(type,app,name){ const prefix={feature:'FEAT',screen:'SCR',api:'API','database-object':'DBO','test-case':'TC'}[type]||'ENT'; return `${prefix}-${appToken(app)}-${slug(name).toUpperCase()}`.slice(0,96); }
function adapter(profile){ return cfg().adapters?.[profile] || {featureDirectories:['features','modules'],screenDirectories:['pages','screens','views'],apiDirectories:['api','routes','controllers','services'],testPatterns:['.test.','.spec.','/tests/','/__tests__/'],databaseDirectories:['models','entities','migrations','database','db']}; }
function segmentAfter(relPath, dirs){ const parts=norm(relPath).split('/'); const lowers=parts.map(x=>x.toLowerCase()); for(const d of dirs||[]){const i=lowers.indexOf(String(d).toLowerCase()); if(i>=0 && parts[i+1]) return parts[i+1];} return null; }
function anySegment(relPath, dirs){ const lowers=norm(relPath).toLowerCase().split('/'); return (dirs||[]).some(d=>lowers.includes(String(d).toLowerCase())); }
function isTest(file,a){ const p='/'+norm(file).toLowerCase(); return (a.testPatterns||[]).some(raw=>p.includes(String(raw).toLowerCase())); }
function cleanStem(file){ return path.basename(file,path.extname(file)).replace(/(page|screen|view|controller|service|repository|routes?|endpoint|test|spec)$/i,'') || path.basename(file,path.extname(file)); }
function endpointEvidence(file){
  const abs=path.join(ROOT,file.path); let text=''; try{text=fs.readFileSync(abs,'utf8');}catch{return [];}
  const found=[]; const add=(method,route)=>{const x=`${String(method).toUpperCase()} ${route||'(route inferred)'}`;if(!found.includes(x))found.push(x);};
  for(const m of text.matchAll(/\b(?:Map|app\.)?(Get|Post|Put|Patch|Delete)\s*\(\s*["'`]([^"'`]+)["'`]/gi)) add(m[1],m[2]);
  for(const m of text.matchAll(/\[(HttpGet|HttpPost|HttpPut|HttpPatch|HttpDelete)(?:\(\s*["']?([^\)"']*)["']?\s*\))?\]/gi)) add(m[1].replace(/^Http/i,''),m[2]||'(attribute route)');
  return found.slice(0,50);
}
function appForFile(filePath,apps){ return apps.filter(a=>a.meta.source_root&&inside(filePath,a.meta.source_root)).sort((a,b)=>String(b.meta.source_root).length-String(a.meta.source_root).length)[0]||null; }
function classify(file,app){
  const a=adapter(app.meta.source_profile); const root=norm(app.meta.source_root); const relative=norm(file.path).slice(root.length).replace(/^\//,'');
  const featureName=segmentAfter(relative,a.featureDirectories);
  let kind='source'; let reason='unclassified';
  if(isTest(relative,a)){kind='test-case';reason='test-pattern';}
  else if(anySegment(relative,a.screenDirectories)||/(Page|Screen|View)\.[^.]+$/i.test(relative)){kind='screen';reason='screen-path';}
  else if(anySegment(relative,a.apiDirectories)||/(Controller|Endpoint|Routes?)\.[^.]+$/i.test(relative)){kind='api';reason='api-path';}
  else if(anySegment(relative,a.databaseDirectories)||/\.sql$/i.test(relative)){kind='database-object';reason='database-path';}
  return {relative,featureName,kind,reason};
}
export function buildInventory({appCode=null}={}){
  const idx=scanSource(); const apps=applications().filter(a=>!appCode||a.code===appCode); if(appCode&&!apps.length) throw new Error(`Application not found: ${appCode}`);
  const rows=[];
  for(const file of idx.files||[]){const app=appForFile(file.path,apps);if(!app)continue;const c=classify(file,app);rows.push({path:file.path,application:app.code,sourceProfile:app.meta.source_profile,relativePath:c.relative,classification:c.kind,classificationReason:c.reason,featureHint:c.featureName||null,language:file.language,symbols:file.symbols||[],imports:file.imports||[],endpoints:c.kind==='api'?endpointEvidence(file):[]});}
  const summary={files:rows.length,applications:[...new Set(rows.map(x=>x.application))].length,classified:rows.filter(x=>x.classification!=='source').length,unclassified:rows.filter(x=>x.classification==='source').length};
  const out={schemaVersion:'1.0',generatedAt:new Date().toISOString(),sourceFingerprint:idx.sourceFingerprint||null,applicationFilter:appCode||null,summary,files:rows}; writeJson(INVENTORY,out); return out;
}
function makeCandidate(type,app,name,evidence,confidence,extra={}){ const key=`${name}|${evidence.map(x=>x.path).sort().join('|')}`; return {candidateId:candidateId(type,app,key),suggestedType:type,suggestedCode:codeFor(type,app,name),suggestedTitle:title(name),application:app,confidence:Number(confidence.toFixed(2)),status:'pending-review',evidence:evidence.map(x=>({path:x.path,reason:x.reason||x.classificationReason||type,details:x.details||x.endpoints||[]})),suggestedRelations:{applications:[app],...(extra.suggestedRelations||{})},...extra}; }
export function buildCandidates({appCode=null}={}){
  let inv=loadJson(INVENTORY,null); const idx=loadSourceIndex(); if(!inv || inv.sourceFingerprint!==idx.sourceFingerprint || (appCode&&inv.applicationFilter!==appCode)) inv=buildInventory({appCode});
  const candidates=[]; const featureMap=new Map();
  for(const f of inv.files){if(!f.featureHint)continue;const key=`${f.application}|${f.featureHint}`;if(!featureMap.has(key))featureMap.set(key,[]);featureMap.get(key).push(f);}
  for(const [key,files] of featureMap){const [app,name]=key.split('|');candidates.push(makeCandidate('feature',app,name,files,0.92));}
  for(const f of inv.files){if(f.classification==='source')continue;const name=cleanStem(f.relativePath);let confidence={screen:0.86,api:0.9,'database-object':0.82,'test-case':0.88}[f.classification]||0.7; if(f.featureHint)confidence=Math.min(0.98,confidence+0.04); const rel={}; if(f.featureHint)rel.features=[codeFor('feature',f.application,f.featureHint)]; candidates.push(makeCandidate(f.classification,f.application,name,[f],confidence,{suggestedRelations:rel}));}
  const unique=[];const seen=new Set();for(const c of candidates.sort((a,b)=>a.candidateId.localeCompare(b.candidateId))){if(seen.has(c.candidateId))continue;seen.add(c.candidateId);unique.push(c);}
  const prev=loadJson(CANDIDATES,{reviews:{},promotions:{}}); const validIds=new Set(unique.map(x=>x.candidateId)); const reviews=Object.fromEntries(Object.entries(prev.reviews||{}).filter(([id])=>validIds.has(id))); const promotions=Object.fromEntries(Object.entries(prev.promotions||{}).filter(([id])=>validIds.has(id)));
  for(const c of unique){if(reviews[c.candidateId])c.status=reviews[c.candidateId].decision==='accepted'?'accepted':'rejected';if(promotions[c.candidateId])c.status='promoted';}
  const out={schemaVersion:'1.0',generatedAt:new Date().toISOString(),sourceFingerprint:inv.sourceFingerprint,applicationFilter:appCode||null,summary:{total:unique.length,feature:unique.filter(x=>x.suggestedType==='feature').length,artifact:unique.filter(x=>x.suggestedType!=='feature').length,pending:unique.filter(x=>x.status==='pending-review').length},candidates:unique,reviews,promotions};writeJson(CANDIDATES,out);return out;
}
export function reviewCandidate({candidateId,decision,reviewer,note=''}){ const data=loadJson(CANDIDATES,null);if(!data)throw new Error('Candidate graph missing; run brownfield:candidates first.');const c=data.candidates.find(x=>x.candidateId===candidateId);if(!c)throw new Error(`Candidate not found: ${candidateId}`);if(!['accepted','rejected'].includes(decision))throw new Error('Decision must be accepted or rejected.');if(cfg().candidatePolicy?.requireReviewer!==false&&!reviewer)throw new Error('Reviewer is required.');data.reviews=data.reviews||{};data.reviews[candidateId]={decision,reviewer:String(reviewer||''),note:String(note||''),reviewedAt:new Date().toISOString()};c.status=decision;writeJson(CANDIDATES,data);return c; }
function entityPath(c){const base=slug(c.suggestedCode);if(c.suggestedType==='feature')return `docs/02-modules/_brownfield/${base}/feature.md`;if(c.suggestedType==='screen')return `docs/05-screens/${base}.md`;if(c.suggestedType==='api')return `docs/07-api/${base}.md`;if(c.suggestedType==='database-object')return `docs/08-database/tables/${base}.md`;if(c.suggestedType==='test-case')return `docs/11-quality/test-cases/${base}.md`;return `docs/00-project/${base}.md`;}
function relationMeta(c){const existing=new Set(scanEntities().entities.map(x=>x.code));const r={applications:[c.application]};for(const [field,values] of Object.entries(c.suggestedRelations||{})){if(field==='applications')continue;const valid=(values||[]).filter(x=>existing.has(x));if(valid.length)r[field]=valid;}return r;}
function entityBody(c){const ev=c.evidence.map(x=>`- \`${x.path}\`${x.details?.length?` — ${x.details.join(', ')}`:''}`).join('\n');const header=`# ${c.suggestedTitle}\n\n> Brownfield origin: reverse-engineered from existing source and explicitly reviewed before promotion.\n\n## Source Evidence\n\n${ev||'- No evidence recorded.'}\n`;
  if(c.suggestedType==='feature')return `${header}\n## Business Goal\n\nConfirm and refine the implemented behaviour represented by this source cluster.\n\n## Actors\n\nTo be reconciled with product knowledge.\n\n## Main Flow\n\n1. Review the existing implementation and record the observed happy path.\n\n## Key Rules\n\n- Source evidence is not a substitute for reviewed business intent.\n\n## Technical Impact\n\n- Application: \`${c.application}\`\n\n## Acceptance Summary\n\n- Canonical behaviour has been reviewed against the existing implementation.\n\n## Assumptions / Known Limitations\n\n- This document was created during brownfield adoption.\n\n## Open Questions\n\n- Resolve any difference between implementation and intended product behaviour.\n`;
  return `${header}\n## Brownfield Summary\n\n- Application: \`${c.application}\`\n- Candidate confidence: ${c.confidence}\n\n## Behaviour / Contract\n\nReview and replace source-derived observations with canonical project intent where required.\n`;
}
export function promoteCandidate({candidateId,reviewer=''}){const data=loadJson(CANDIDATES,null);if(!data)throw new Error('Candidate graph missing; run brownfield:candidates first.');const c=data.candidates.find(x=>x.candidateId===candidateId);if(!c)throw new Error(`Candidate not found: ${candidateId}`);const review=data.reviews?.[candidateId];if(cfg().candidatePolicy?.requireReviewBeforePromote!==false&&review?.decision!=='accepted')throw new Error(`Candidate ${candidateId} must be accepted before promotion.`);if(scanEntities().entities.some(x=>x.code===c.suggestedCode))throw new Error(`Canonical entity already exists: ${c.suggestedCode}`);const date=new Date().toISOString().slice(0,10);const meta={code:c.suggestedCode,type:c.suggestedType,title:c.suggestedTitle,status:c.suggestedType==='test-case'?'ready':'implemented',owner:reviewer||review?.reviewer||'Engineering',created_at:date,updated_at:date,last_reviewed_at:date,tags:['brownfield','reverse-engineered'],related:relationMeta(c)};if(c.suggestedType==='feature'){meta.spec_level='lightweight';meta.target_maturity='production';}const rel=entityPath(c);writeMarkdownEntity(rel,meta,entityBody(c));data.promotions=data.promotions||{};data.promotions[candidateId]={entityCode:c.suggestedCode,path:rel,promotedAt:new Date().toISOString(),reviewer:reviewer||review?.reviewer||''};c.status='promoted';writeJson(CANDIDATES,data);return {candidate:c,path:rel};}
export function reconcile({appCode=null}={}){const inv=loadJson(INVENTORY,null);const cand=loadJson(CANDIDATES,null);if(!inv||!cand)throw new Error('Brownfield inventory/candidates missing. Run brownfield:inventory and brownfield:candidates first.');const policy=cfg();const findings=[];const add=(severity,code,message,ref=null)=>findings.push({severity,code,message,ref});const candidates=(cand.candidates||[]).filter(c=>!appCode||c.application===appCode);const entities=new Set(scanEntities().entities.map(e=>e.code));const high=Number(policy.candidatePolicy?.highConfidence??0.85);for(const c of candidates){const review=cand.reviews?.[c.candidateId];const promo=cand.promotions?.[c.candidateId];if(!review && c.confidence>=high)add('high','UNREVIEWED_CANDIDATE',`High-confidence candidate ${c.candidateId} has not been reviewed.`,c.candidateId);else if(!review)add('warning','UNREVIEWED_CANDIDATE',`Candidate ${c.candidateId} has not been reviewed.`,c.candidateId);if(c.confidence<Number(policy.candidatePolicy?.mediumConfidence??0.6))add('warning','LOW_CONFIDENCE_MAPPING',`Candidate ${c.candidateId} confidence=${c.confidence}.`,c.candidateId);if(review?.decision==='accepted'&&!promo)add('high','ACCEPTED_NOT_PROMOTED',`Accepted candidate ${c.candidateId} has not been promoted.`,c.candidateId);if(promo&&!entities.has(promo.entityCode))add('high','PROMOTED_ENTITY_MISSING',`Promoted entity ${promo.entityCode} is missing.`,c.candidateId);for(const e of c.evidence||[])if(!fs.existsSync(path.join(ROOT,e.path)))add('high','MISSING_EVIDENCE',`Evidence file no longer exists: ${e.path}`,c.candidateId);}
  const appFiles=(inv.files||[]).filter(f=>!appCode||f.application===appCode);const evidencePaths=new Set(candidates.flatMap(c=>(c.evidence||[]).map(e=>e.path)));for(const f of appFiles)if(f.classification!=='source'&&!evidencePaths.has(f.path))add('warning','UNCLASSIFIED_SOURCE',`Classified source is not represented by a candidate: ${f.path}`,f.path);
  const block=new Set(policy.reconciliation?.blockSeverities||['high']);const pass=!findings.some(f=>block.has(f.severity));const out={schemaVersion:'1.0',generatedAt:new Date().toISOString(),applicationFilter:appCode||null,sourceFingerprint:inv.sourceFingerprint,pass,summary:{candidates:candidates.length,findings:findings.length,high:findings.filter(x=>x.severity==='high').length,warnings:findings.filter(x=>x.severity==='warning').length},findings};writeJson(RECONCILIATION,out);return out;}
export function baselineGate({appCode=null}={}){const checks=[];const add=(code,pass,message)=>checks.push({code,pass,message});const adopted=applications().filter(a=>(a.meta.source_origin==='existing'||loadJson('.project-docs/source.lock.json',{applications:{}}).applications?.[a.code]?.origin==='existing')&&(!appCode||a.code===appCode));add('APPLICATION_ADOPTED',adopted.length>0,adopted.length?`${adopted.length} existing application boundary/boundaries registered.`:'No existing application boundary registered.');const inv=loadJson(INVENTORY,null);add('INVENTORY',!!inv,'Brownfield inventory exists.');const cand=loadJson(CANDIDATES,null);add('CANDIDATES',!!cand,'Brownfield candidate graph exists.');const rec=loadJson(RECONCILIATION,null);add('RECONCILIATION',!!rec&&rec.pass===true,rec?`Reconciliation ${rec.pass?'passes':'has blocking findings'} (${rec.summary?.findings||0} finding(s)).`:'Reconciliation report missing.');if(cand){const high=Number(cfg().candidatePolicy?.highConfidence??0.85);const scoped=(cand.candidates||[]).filter(c=>!appCode||c.application===appCode);const unreviewed=scoped.filter(c=>c.confidence>=high&&!cand.reviews?.[c.candidateId]);add('HIGH_CONFIDENCE_REVIEW',unreviewed.length===0,`${unreviewed.length} high-confidence candidate(s) awaiting review.`);const acceptedMissing=scoped.filter(c=>cand.reviews?.[c.candidateId]?.decision==='accepted'&&!cand.promotions?.[c.candidateId]);add('ACCEPTED_PROMOTION',acceptedMissing.length===0,`${acceptedMissing.length} accepted candidate(s) awaiting promotion.`);}return {pass:checks.every(x=>x.pass),checks};}
export function createBrownfieldBaseline({name='brownfield-initial-baseline',actor,note='',appCode=null}={}){const gate=baselineGate({appCode});if(!gate.pass)throw new Error('Brownfield Baseline Gate failed; run gate:baseline for details.');const b=createBaseline({name,actor,note:note||'Initial accepted brownfield code/documentation baseline.'});const p=loadJson('project.profile.json',{});p.adoption={...(p.adoption||{}),mode:'brownfield',strategy:p.adoption?.strategy||cfg().adoption?.defaultStrategy||'adopt-in-place',baselineStatus:'reconciled',baselineId:b.id,reconciledAt:new Date().toISOString()};writeJson('project.profile.json',p);return b;}
export function markBrownfieldAdoption({strategy=null}={}){const p=loadJson('project.profile.json',{});p.adoption={...(p.adoption||{}),mode:'brownfield',strategy:strategy||p.adoption?.strategy||cfg().adoption?.defaultStrategy||'adopt-in-place',baselineStatus:p.adoption?.baselineStatus==='reconciled'?'reconciled':'in-progress'};writeJson('project.profile.json',p);return p.adoption;}
export function brownfieldStatus(){const p=loadJson('project.profile.json',{});const inv=loadJson(INVENTORY,null),cand=loadJson(CANDIDATES,null),rec=loadJson(RECONCILIATION,null);return {adoption:p.adoption||{mode:'greenfield',baselineStatus:'not-required'},inventory:inv?.summary||null,candidates:cand?.summary||null,reconciliation:rec?{pass:rec.pass,...rec.summary}:null,baselineGate:baselineGate({})};}
export function buildRefactorPlan({appCode=null}={}){const apps=applications().filter(a=>(a.meta.source_origin==='existing'||loadJson('.project-docs/source.lock.json',{applications:{}}).applications?.[a.code]?.origin==='existing')&&(!appCode||a.code===appCode));if(!apps.length)throw new Error('No adopted existing application found.');const moves=[];for(const app of apps){const p=String(app.meta.source_profile||'');const type=String(app.meta.application_type||'');let target=app.meta.source_root;if(type==='web')target='apps/web';else if(type==='mobile')target=p.includes('ios')?'apps/mobile-ios':p.includes('android')?'apps/mobile-android':'apps/mobile';else if(type==='api')target='apps/api';else if(type==='worker')target='apps/worker';moves.push({application:app.code,from:String(app.meta.source_root),to:target,needed:norm(app.meta.source_root)!==norm(target),reason:'Normalize deployable application boundary into canonical apps/ root.'});}const plan={schemaVersion:'1.0',generatedAt:new Date().toISOString(),status:'proposal',requiresWorkPlan:true,automaticExecutionAllowed:false,moves,requiredUpdates:['imports/project references','workspace/build configuration','CI/CD paths','Docker/deployment paths','test paths','Application source_root and source.lock provenance'],verification:['build','automated tests','source:check','source:scan','doctor','qa'],note:'This proposal does not move files. Convert accepted moves into a reviewed WorkPlan before execution.'};writeJson(REFACTOR_PLAN,plan);return plan;}
