import fs from 'node:fs';
import path from 'node:path';
import { ROOT, loadJson, writeJson, scanEntities, fileHash, sha256 } from './common.mjs';
import { loadSourceIndex } from './source-intelligence.mjs';

const INDEX_DIR='.project-docs/indexes';
function cfg(){return loadJson('registry/local-engine.json',{indexes:{},search:{},query:{},context:{}});}
function asArray(v){return Array.isArray(v)?v:(v===undefined||v===null||v===''?[]:[v]);}
export function entityFingerprint(){const {entities}=scanEntities();return sha256(entities.map(e=>`${e.path}:${fileHash(path.join(ROOT,e.path))}`).sort().join('\n'));}
export function buildKnowledgeIndexes(){
  const {entities}=scanEntities(); const fingerprint=entityFingerprint(); const byCode=new Map(entities.map(e=>[e.code,e]));
  const entityRows=entities.map(e=>({uid:e.uid||null,code:e.code,type:e.type,title:e.title,status:e.status,path:e.path,revision:e.revision||0,tags:asArray(e.meta.tags),meta:e.meta}));
  const edges=[]; for(const e of entities)for(const [field,raw] of Object.entries(e.meta.related||{}))for(const target of asArray(raw).map(String))if(byCode.has(target))edges.push({from:e.code,to:target,field,fromUid:e.uid||null,toUid:byCode.get(target).uid||null});
  const outgoing={},incoming={}; for(const edge of edges){(outgoing[edge.from]??=[]).push(edge);(incoming[edge.to]??=[]).push(edge);}
  const maxBody=Number(cfg().indexes?.maxBodyChars||200000); const searchRows=entities.map(e=>({code:e.code,uid:e.uid||null,type:e.type,title:e.title,status:e.status,path:e.path,tags:asArray(e.meta.tags),text:[e.code,e.uid,e.type,e.title,e.status,...asArray(e.meta.tags),JSON.stringify(e.meta),e.body.slice(0,maxBody)].filter(Boolean).join('\n').toLowerCase()}));
  const base={schemaVersion:'1.0',generatedAt:new Date().toISOString(),entityFingerprint:fingerprint};
  writeJson(`${INDEX_DIR}/entity-index.json`,{...base,entities:entityRows}); writeJson(`${INDEX_DIR}/relation-index.json`,{...base,edges,outgoing,incoming}); writeJson(`${INDEX_DIR}/search-index.json`,{...base,documents:searchRows});
  return {entities:entityRows,edges,documents:searchRows,fingerprint};
}
export function loadKnowledgeIndexes({rebuildIfStale=true}={}){
  const current=entityFingerprint(); const entity=loadJson(`${INDEX_DIR}/entity-index.json`,null); const relation=loadJson(`${INDEX_DIR}/relation-index.json`,null); const search=loadJson(`${INDEX_DIR}/search-index.json`,null);
  if(!entity||!relation||!search||entity.entityFingerprint!==current||relation.entityFingerprint!==current||search.entityFingerprint!==current){if(rebuildIfStale)return buildKnowledgeIndexes();}
  return {entities:entity?.entities||[],edges:relation?.edges||[],documents:search?.documents||[],fingerprint:entity?.entityFingerprint||null,relationIndex:relation,searchIndex:search};
}
function tokenizeExpr(input){
  const s=String(input||'').trim(); if(!s)return [];
  const tokens=[]; let i=0; const isWord=c=>/[A-Za-z0-9_.-]/.test(c);
  while(i<s.length){if(/\s/.test(s[i])){i++;continue;} if(s[i]==='('||s[i]===')'){tokens.push({type:s[i]});i++;continue;}
    const kw=s.slice(i).match(/^(AND|OR|NOT)\b/i); if(kw){tokens.push({type:kw[1].toUpperCase()});i+=kw[0].length;continue;}
    let start=i; while(i<s.length&&isWord(s[i]))i++; if(i===start)throw new Error(`Unexpected token near: ${s.slice(i,Math.min(i+20,s.length))}`); const field=s.slice(start,i);
    while(/\s/.test(s[i]||''))i++; const ops=['!=','~=','^=','$=','>=','<=','=','>','<']; const op=ops.find(x=>s.startsWith(x,i)); if(!op)throw new Error(`Expected operator after ${field}`); i+=op.length; while(/\s/.test(s[i]||''))i++;
    let value=''; if(s[i]==='"'||s[i]==="'"){const q=s[i++];while(i<s.length&&s[i]!==q){if(s[i]==='\\'&&i+1<s.length){value+=s[i+1];i+=2;}else value+=s[i++];}if(s[i]!==q)throw new Error('Unterminated quoted value');i++;}else{const vstart=i;while(i<s.length&&!/\s|\(|\)/.test(s[i]))i++;value=s.slice(vstart,i);} tokens.push({type:'COND',field,op,value});
  } return tokens;
}
function parseExpr(input){const t=tokenizeExpr(input);let i=0;const peek=x=>t[i]?.type===x;const take=x=>peek(x)?t[i++]:null;function primary(){if(take('(')){const x=or();if(!take(')'))throw new Error('Missing )');return x;}const c=take('COND');if(!c)throw new Error('Expected condition');return {kind:'cond',...c};}function not(){if(take('NOT'))return {kind:'not',value:not()};return primary();}function and(){let n=not();while(take('AND'))n={kind:'and',left:n,right:not()};return n;}function or(){let n=and();while(take('OR'))n={kind:'or',left:n,right:and()};return n;}const ast=t.length?or():null;if(i!==t.length)throw new Error('Unexpected trailing expression');return ast;}
function fieldValue(e,field){if(field==='type'||field==='entityType')return e.type;if(field==='tag'||field==='tags')return asArray(e.meta.tags);if(field==='code'||field==='uid'||field==='title'||field==='status'||field==='path'||field==='revision')return e[field];if(field.startsWith('data.'))return e.meta[field.slice(5)];return e.meta[field];}
function compare(actual,op,expected){const vals=Array.isArray(actual)?actual:[actual];const cmp=v=>{const a=v===undefined||v===null?'':String(v),b=String(expected);if(op==='=')return a.toLowerCase()===b.toLowerCase();if(op==='!=')return a.toLowerCase()!==b.toLowerCase();if(op==='~=')return a.toLowerCase().includes(b.toLowerCase());if(op==='^=')return a.toLowerCase().startsWith(b.toLowerCase());if(op==='$=')return a.toLowerCase().endsWith(b.toLowerCase());const an=Number(a),bn=Number(b),numeric=a!==''&&b!==''&&!Number.isNaN(an)&&!Number.isNaN(bn);const x=numeric?an:a,y=numeric?bn:b;return op==='>'?x>y:op==='>='?x>=y:op==='<'?x<y:op==='<='?x<=y:false;};return op==='!='?vals.every(cmp):vals.some(cmp);}
function evalAst(ast,e){if(!ast)return true;if(ast.kind==='cond')return compare(fieldValue(e,ast.field),ast.op,ast.value);if(ast.kind==='not')return !evalAst(ast.value,e);if(ast.kind==='and')return evalAst(ast.left,e)&&evalAst(ast.right,e);if(ast.kind==='or')return evalAst(ast.left,e)||evalAst(ast.right,e);return false;}
function graphScope(rootCode,{direction='both',relations=[],maxDepth=2}={}){const idx=loadKnowledgeIndexes();const allowed=new Set(asArray(relations).map(String));const adj=new Map();const add=(a,b,field)=>{if(allowed.size&&!allowed.has(field))return;(adj.get(a)||adj.set(a,[]).get(a)).push({to:b,field});};for(const e of idx.edges){if(direction==='out'||direction==='both')add(e.from,e.to,e.field);if(direction==='in'||direction==='both')add(e.to,e.from,e.field);}const seen=new Set([rootCode]);let q=[{code:rootCode,depth:0}];while(q.length){const cur=q.shift();if(cur.depth>=Number(maxDepth))continue;for(const edge of adj.get(cur.code)||[])if(!seen.has(edge.to)){seen.add(edge.to);q.push({code:edge.to,depth:cur.depth+1});}}return seen;}
export function queryEntities(expression,options={}){const {entities}=scanEntities();const ast=parseExpr(expression);let rows=entities.filter(e=>evalAst(ast,e));if(options.relatedTo){const scope=graphScope(String(options.relatedTo),{direction:options.direction||'both',relations:options.relations||[],maxDepth:Number(options.maxDepth||2)});rows=rows.filter(e=>scope.has(e.code));}const limit=Number(options.limit||cfg().query?.defaultLimit||100);return rows.slice(0,limit);}
export function searchKnowledge(text,options={}){const idx=loadKnowledgeIndexes();const terms=String(text||'').toLowerCase().split(/\s+/).filter(x=>x.length>=Number(cfg().search?.minTokenLength||2));const types=new Set(asArray(options.types).map(String));const scored=[];for(const d of idx.documents){if(types.size&&!types.has(d.type))continue;let score=0;for(const term of terms){if(d.code.toLowerCase()===term)score+=12;if((d.title||'').toLowerCase().includes(term))score+=6;const count=(d.text.match(new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length;score+=Math.min(count,10);}if(score>0)scored.push({...d,score});}scored.sort((a,b)=>b.score-a.score||a.code.localeCompare(b.code));return scored.slice(0,Number(options.limit||cfg().search?.defaultLimit||20));}
export function buildContext(entityRef,options={}){const {entities}=scanEntities();const root=entities.find(e=>e.code===String(entityRef)||e.uid===String(entityRef));if(!root)throw new Error(`Entity not found: ${entityRef}`);const idx=loadKnowledgeIndexes();const direction=options.direction||'both',maxDepth=Number(options.maxDepth||cfg().context?.defaultMaxDepth||2),maxEntities=Number(options.maxEntities||cfg().context?.defaultMaxEntities||40);const adj=new Map();const add=(a,b,field)=>{(adj.get(a)||adj.set(a,[]).get(a)).push({to:b,field});};for(const e of idx.edges){if(direction==='out'||direction==='both')add(e.from,e.to,e.field);if(direction==='in'||direction==='both')add(e.to,e.from,e.field);}const byCode=new Map(entities.map(e=>[e.code,e]));const seen=new Set([root.code]);const related=[];const q=[{code:root.code,depth:0,path:[root.code]}];while(q.length&&related.length<maxEntities-1){const cur=q.shift();if(cur.depth>=maxDepth)continue;for(const edge of adj.get(cur.code)||[]){if(seen.has(edge.to))continue;seen.add(edge.to);const e=byCode.get(edge.to);if(!e)continue;const row={code:e.code,uid:e.uid||null,type:e.type,title:e.title,status:e.status,path:e.path,depth:cur.depth+1,via:edge.field,bodySummary:e.body.trim().slice(0,1200)};related.push(row);q.push({code:e.code,depth:cur.depth+1,path:[...cur.path,e.code]});if(related.length>=maxEntities-1)break;}}
  let sourceEvidence=[];try{const src=loadSourceIndex({rebuildIfMissing:false});for(const f of src.files||[]){const refs=(f.entityRefs||[]).filter(r=>r.code===root.code||related.some(x=>x.code===r.code));if(refs.length)sourceEvidence.push({path:f.path,language:f.language,entityRefs:refs,dependencies:f.dependencies||[],dependents:f.dependents||[]});}}catch{}
  return {schemaVersion:'1.0',generatedAt:new Date().toISOString(),root:{code:root.code,uid:root.uid||null,type:root.type,title:root.title,status:root.status,path:root.path,bodySummary:root.body.trim().slice(0,1600)},related,sourceEvidence:sourceEvidence.slice(0,100)};
}
export function viewConfig(){return loadJson('registry/views.json',{views:{}});}
