#!/usr/bin/env node
// Builds a compact, task-specific "agent pack" so an AI agent does NOT have to read kit/ (templates, standards, registry).
// Everything is derived from the kit's own registry/templates, so it cannot drift from them.
// Usage: node scripts/agent-pack.mjs --types feature,requirement,business-rule,api,test-case [--rules 1,4,6,12,25,27,33] [--full-templates] [--out name]
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const flag = (k) => process.argv.includes('--' + k);
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const json = (p) => JSON.parse(read(p));

const types = arg('types', 'feature,requirement,business-rule,screen,api,database-object,test-case').split(',').map((s) => s.trim());
const ruleNos = new Set(arg('rules', '1,3,4,6,12,25,27,33').split(',').map(Number));
const name = arg('out', 'author-' + types.join('+'));

const entityTypes = json('kit/registry/entity-types.json').types;
const relations = json('kit/registry/relation-map.json').relations;
const bundle = json('kit/registry/documentation-bundle.json').entityTargets;

// --- rules subset (parsed from the numbered list in ai-agent-rules.md)
const rules = read('kit/standards/ai-agent-rules.md').split('\n').map((l) => /^(\d+)\.\s+(.*)/.exec(l)).filter(Boolean).filter((m) => ruleNos.has(Number(m[1])));

const where = (t) => {
  const b = bundle[t]; if (!b) return '(see kit/registry/documentation-bundle.json)';
  return b.strategy === 'module' ? `${b.directory}/<CODE>/module.md`
    : b.strategy === 'feature' ? `${b.directory}/<MODULE-CODE>/<CODE>/feature.md`
    : b.strategy === 'preserve-subdir' ? `${b.directory}/${b.fallbackSubdir || b.subdirs?.[0] || ''}/<CODE>.md`.replace('//', '/')
    : `${b.directory}/<CODE>.md`;
};

function compactTemplate(t, full) {
  const raw = read(`kit/templates/${t}-template.md`);
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(raw); if (!m) return raw;
  const fmLines = m[1].split('\n'), body = m[2];
  const keep = []; for (const l of fmLines) { if (l.startsWith('related:')) break; if (/^(uid|revision):/.test(l)) continue; keep.push(l); }
  const rel = relations.filter((r) => r.from === t).map((r) => `${r.field}→${r.to}`);
  let outBody;
  if (full) outBody = body.trim();
  else outBody = body.split('\n').filter((l) => /^#{1,3} /.test(l) || /^\|/.test(l) && !/^\|[-:| ]+\|$/.test(l) || /^(Use stable|Recommended|Common `Type`|For critical)/.test(l)).join('\n');
  return [`### ${t}`, `File: \`${where(t)}\`  ·  statuses: ${entityTypes[t]?.statuses?.join(' | ')} (initial: ${entityTypes[t]?.initialStatus})`,
    '```yaml', ...keep, `related:   # only these keys exist for ${t}: ${rel.join(', ') || '(none)'}`, '```', outBody].join('\n');
}

const out = [];
out.push(`# Agent pack: ${name}`, '', '> Generated by tools/scripts/agent-pack.mjs from kit/registry + kit/templates. Do NOT read kit/ for authoring; this pack replaces it.', '');
out.push('## Rules', ...rules.map((m) => `${m[1]}. ${m[2]}`), '');
out.push('## Conventions',
  '- `uid`/`revision` may be omitted: run `cd tools && npm run entity:identity-backfill -- --apply` afterwards.',
  '- Codes: MOD-<DOMAIN>, FEAT-<DOMAIN>-<n>, REQ-<DOMAIN>-NNN, BR-<DOMAIN>-NNN, SCR-<n>, FLOW-<DOMAIN>-<n>, API-<DOMAIN>-<n>, DB-<OBJECT>, TC-<DOMAIN>-<n>-NNN. Codes never change.',
  '- Frontmatter lists must stay on ONE line: `tests: [A, B]` (the kit parser breaks on wrapped YAML lists). Dates unquoted `YYYY-MM-DD`.',
  '- Requirement AC rows use stable ids `AC-01`; tests reference `acceptance_criteria: [REQ-X-001#AC-01]`, `business_rule_cases: [BR-X-001#positive]`.',
  '- Link only along the relation keys listed per type; do not over-link (warning above 20 outgoing links). Feature links tests via requirements; list 1–2 smoke tests only.',
  '- After writing: `cd tools && npm run docs:validate && npm run verification:check`.', '');
out.push('## Entity types', ...types.map((t) => compactTemplate(t, flag('full-templates'))));
const text = out.join('\n') + '\n';
const dir = path.join(ROOT, '.project-docs/agent-packs'); fs.mkdirSync(dir, { recursive: true });
const file = path.join(dir, name + '.md'); fs.writeFileSync(file, text);
const bytes = Buffer.byteLength(text);
console.log(`Wrote ${path.relative(ROOT, file)}: ${bytes} bytes ≈ ${Math.round(bytes / 3.8)} tokens (est.). types=${types.join(',')} rules=${[...ruleNos].join(',')}`);
