import { parseArgs } from '../lib/common.mjs';
import { buildInventory, buildCandidates, reviewCandidate, promoteCandidate, reconcile, baselineGate, createBrownfieldBaseline, brownfieldStatus, buildRefactorPlan } from '../lib/brownfield.mjs';
const action=process.argv[2]||'status';const args=parseArgs(process.argv.slice(3));const req=n=>{if(!args[n])throw new Error(`Missing --${n}`);return String(args[n]);};
try{
  if(action==='inventory'){const r=buildInventory({appCode:args.app?String(args.app):null});console.log(`Brownfield inventory: ${r.summary.files} file(s), ${r.summary.classified} classified, ${r.summary.unclassified} unclassified, ${r.summary.applications} application(s).`);}
  else if(action==='candidates'){const r=buildCandidates({appCode:args.app?String(args.app):null});console.log(`Brownfield candidates: ${r.summary.total} total (${r.summary.feature} feature, ${r.summary.artifact} artifact), ${r.summary.pending} pending review.`);if(args.json)console.log(JSON.stringify(r,null,2));}
  else if(action==='review'){const c=reviewCandidate({candidateId:req('candidate'),decision:req('decision'),reviewer:req('reviewer'),note:String(args.note||'')});console.log(`Reviewed ${c.candidateId}: ${c.status}.`);}
  else if(action==='promote'){const r=promoteCandidate({candidateId:req('candidate'),reviewer:String(args.reviewer||'')});console.log(`Promoted ${r.candidate.candidateId} -> ${r.candidate.suggestedCode} (${r.path}).`);}
  else if(action==='reconcile'){const r=reconcile({appCode:args.app?String(args.app):null});console.log(`Brownfield reconciliation: ${r.pass?'PASS':'FAIL'}; ${r.summary.findings} finding(s), ${r.summary.high} high, ${r.summary.warnings} warning(s).`);for(const f of r.findings)console.log(`[${f.severity.toUpperCase()}] ${f.code}: ${f.message}`);if(!r.pass)process.exitCode=1;}
  else if(action==='baseline-gate'){const r=baselineGate({appCode:args.app?String(args.app):null});console.log(`BROWNFIELD BASELINE: ${r.pass?'PASS':'FAIL'}`);for(const c of r.checks)console.log(`[${c.pass?'PASS':'FAIL'}] ${c.code}: ${c.message}`);if(!r.pass)process.exitCode=1;}
  else if(action==='baseline-create'){const b=createBrownfieldBaseline({name:String(args.name||'brownfield-initial-baseline'),actor:req('actor'),note:String(args.note||''),appCode:args.app?String(args.app):null});console.log(`Created brownfield baseline ${b.id}: ${b.summary.files} file(s), ${b.summary.entities} entity record(s).`);}
  else if(action==='refactor-plan'){const p=buildRefactorPlan({appCode:args.app?String(args.app):null});console.log(`Brownfield refactor plan: ${p.moves.length} application move proposal(s); execution disabled until reviewed WorkPlan.`);for(const m of p.moves)console.log(`${m.application}: ${m.from} -> ${m.to} ${m.needed?'[MOVE]':'[ALREADY CANONICAL]'}`);}
  else if(action==='status'){const s=brownfieldStatus();console.log(`Brownfield status: mode=${s.adoption.mode||'greenfield'}, strategy=${s.adoption.strategy||'-'}, baseline=${s.adoption.baselineStatus||'not-required'}`);console.log(`Inventory: ${s.inventory?`${s.inventory.files} file(s)`:'missing'}`);console.log(`Candidates: ${s.candidates?`${s.candidates.total} total, ${s.candidates.pending} pending`:'missing'}`);console.log(`Reconciliation: ${s.reconciliation?(s.reconciliation.pass?'PASS':'FAIL'):'missing'}`);console.log(`Baseline gate: ${s.baselineGate.pass?'PASS':'FAIL'}`);if(args.json)console.log(JSON.stringify(s,null,2));}
  else {console.log('brownfield-tool commands: inventory [--app APP-X], candidates [--app APP-X], review --candidate ID --decision accepted|rejected --reviewer NAME [--note TEXT], promote --candidate ID [--reviewer NAME], reconcile [--app APP-X], baseline-gate [--app APP-X], baseline-create --actor NAME [--name NAME] [--app APP-X], refactor-plan [--app APP-X], status');process.exitCode=1;}
}catch(e){console.error(`[ERROR] ${e.message}`);process.exitCode=1;}
