#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { loadConfig, projectRoot, scanDocuments, buildRelations, codeIndex, docUrl, ensureDir, escapeHtml, posix, slugify } from './lib/core.mjs';

const config = await loadConfig();
const siteDir = path.resolve(projectRoot, config.siteDir);
await fs.rm(siteDir,{recursive:true,force:true});
await ensureDir(path.join(siteDir,'assets'));
const docs=await scanDocuments(config);const entities=docs.filter(d=>d.isEntity);const byCode=codeIndex(entities);const graph=buildRelations(docs);
const outputFileFor=(d)=>docUrl(d.relPath);
const hrefFromOutput=(from,target)=>posix(path.relative(path.dirname(path.join(siteDir,from)),path.join(siteDir,target)));
const pageHref=(from,page)=>hrefFromOutput(from,page);

function rewriteHref(doc,outFile,href){
  if(!href||/^(https?:|mailto:|tel:|#|data:)/i.test(href)) return href;
  const hashIndex=href.indexOf('#'); const targetPart=hashIndex>=0?href.slice(0,hashIndex):href; const hash=hashIndex>=0?href.slice(hashIndex):'';
  if(targetPart&&/\.md$/i.test(targetPart)){
    const targetAbs=path.resolve(path.dirname(doc.absPath),decodeURIComponent(targetPart));const targetRel=posix(path.relative(projectRoot,targetAbs));return hrefFromOutput(outFile,docUrl(targetRel))+hash;
  }
  return href;
}
function renderInline(text,doc,outFile){
  let s=escapeHtml(text);
  s=s.replace(/`([^`]+)`/g,'<code>$1</code>');
  s=s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,href)=>`<a href="${escapeHtml(rewriteHref(doc,outFile,href.replaceAll('&amp;','&')))}">${label}</a>`);
  s=s.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
  s=s.replace(/__([^_]+)__/g,'<strong>$1</strong>');
  s=s.replace(/(^|\s)\*([^*]+)\*(?=\s|$)/g,'$1<em>$2</em>');
  return s;
}
function isTableSeparator(line){return /^\s*\|?(\s*:?-{3,}:?\s*\|)+\s*:?-{3,}:?\s*\|?\s*$/.test(line);}
function splitTable(line){return line.trim().replace(/^\|/,'').replace(/\|$/,'').split('|').map(x=>x.trim());}
function renderMarkdown(content,doc,outFile){
  const lines=content.replace(/\r\n/g,'\n').split('\n'); let html=''; let i=0;
  while(i<lines.length){const line=lines[i];
    if(/^```/.test(line.trim())){const info=line.trim().slice(3).trim();const block=[];i++;while(i<lines.length&&!/^```/.test(lines[i].trim())){block.push(lines[i]);i++;}i++;
      if(info.toLowerCase()==='mermaid'){const src=block.join('\n');html+=`<div class="diagram-wrap"><div class="diagram-toolbar"><span>Mermaid diagram</span><button type="button" data-copy-mermaid>Copy source</button></div><pre class="mermaid">${escapeHtml(src)}</pre><template class="mermaid-source">${escapeHtml(src)}</template></div>`;}
      else html+=`<pre class="code-block"><code class="language-${escapeHtml(info||'text')}">${escapeHtml(block.join('\n'))}</code></pre>`;continue;}
    if(!line.trim()){i++;continue;}
    const h=line.match(/^(#{1,6})\s+(.+)$/);if(h){const level=h[1].length;const text=h[2].trim();html+=`<h${level} id="${slugify(text)}">${renderInline(text,doc,outFile)}</h${level}>`;i++;continue;}
    if(i+1<lines.length&&line.includes('|')&&isTableSeparator(lines[i+1])){const headers=splitTable(line);i+=2;const rows=[];while(i<lines.length&&lines[i].includes('|')&&lines[i].trim()){rows.push(splitTable(lines[i]));i++;}html+='<div class="table-wrap"><table><thead><tr>'+headers.map(c=>`<th>${renderInline(c,doc,outFile)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+headers.map((_,idx)=>`<td>${renderInline(r[idx]||'',doc,outFile)}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>';continue;}
    if(/^>\s?/.test(line)){const q=[];while(i<lines.length&&/^>\s?/.test(lines[i])){q.push(lines[i].replace(/^>\s?/,''));i++;}html+=`<blockquote>${q.map(x=>renderInline(x,doc,outFile)).join('<br>')}</blockquote>`;continue;}
    if(/^\s*[-*+]\s+/.test(line)){const items=[];while(i<lines.length&&/^\s*[-*+]\s+/.test(lines[i])){items.push(lines[i].replace(/^\s*[-*+]\s+/,''));i++;}html+='<ul>'+items.map(x=>`<li>${renderInline(x,doc,outFile)}</li>`).join('')+'</ul>';continue;}
    if(/^\s*\d+\.\s+/.test(line)){const items=[];while(i<lines.length&&/^\s*\d+\.\s+/.test(lines[i])){items.push(lines[i].replace(/^\s*\d+\.\s+/,''));i++;}html+='<ol>'+items.map(x=>`<li>${renderInline(x,doc,outFile)}</li>`).join('')+'</ol>';continue;}
    if(/^---+$/.test(line.trim())){html+='<hr>';i++;continue;}
    const para=[line.trim()];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6})\s+/.test(lines[i])&&!/^```/.test(lines[i].trim())&&!/^>\s?/.test(lines[i])&&!/^\s*[-*+]\s+/.test(lines[i])&&!/^\s*\d+\.\s+/.test(lines[i])&&!(i+1<lines.length&&lines[i].includes('|')&&isTableSeparator(lines[i+1]))){para.push(lines[i].trim());i++;}html+=`<p>${renderInline(para.join(' '),doc,outFile)}</p>`;
  }
  return html;
}
function navTree(currentOut){const groups=new Map();for(const d of docs){if(!groups.has(d.section))groups.set(d.section,[]);groups.get(d.section).push(d);}const keys=[...groups.keys()].sort();return keys.map(key=>{const items=groups.get(key).sort((a,b)=>a.title.localeCompare(b.title));return `<details class="nav-group" ${items.some(d=>outputFileFor(d)===currentOut)?'open':''}><summary>${escapeHtml(key)}</summary>${items.map(d=>`<a class="nav-doc ${outputFileFor(d)===currentOut?'active':''}" href="${hrefFromOutput(currentOut,outputFileFor(d))}">${escapeHtml(d.code||d.title)}</a>`).join('')}</details>`;}).join('');}

let mermaidScript='';
const vendorMermaid=path.join(projectRoot,'tools','vendor','mermaid.min.js');
try{await fs.access(vendorMermaid);await fs.copyFile(vendorMermaid,path.join(siteDir,'assets','mermaid.min.js'));mermaidScript='<script src="__MERMAID_LOCAL__"></script>';}catch{mermaidScript='<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>';}
function baseLayout({title,currentOut,body,subtitle='',extraClass=''}){const css=pageHref(currentOut,'assets/site.css'),js=pageHref(currentOut,'assets/site.js');const mermaidTag=mermaidScript.replace('__MERMAID_LOCAL__',pageHref(currentOut,'assets/mermaid.min.js'));return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} · ${escapeHtml(config.siteTitle)}</title><link rel="stylesheet" href="${css}"></head><body class="${extraClass}"><header class="topbar"><button class="icon-btn" id="sidebarToggle">☰</button><a class="brand" href="${pageHref(currentOut,'index.html')}">${escapeHtml(config.siteTitle)}</a><nav class="topnav"><a href="${pageHref(currentOut,'catalog.html')}">Catalog</a><a href="${pageHref(currentOut,'traceability.html')}">Traceability</a><a href="${pageHref(currentOut,'graph.html')}">Graph</a><a href="${pageHref(currentOut,'flows.html')}">Diagrams</a></nav><button class="search-btn" id="searchOpen">Search <kbd>/</kbd></button><button class="icon-btn" id="themeToggle">◐</button></header><div class="shell"><aside class="sidebar" id="sidebar"><div class="sidebar-tools"><input id="navFilter" placeholder="Filter docs…"></div>${navTree(currentOut)}</aside><main class="main"><div class="page-head"><h1>${escapeHtml(title)}</h1>${subtitle?`<p>${escapeHtml(subtitle)}</p>`:''}</div>${body}</main></div><div class="search-modal" id="searchModal" hidden><div class="search-panel"><div class="search-row"><input id="searchInput" placeholder="Search code, title, content…"><button id="searchClose">Close</button></div><div id="searchResults"></div></div></div>${mermaidTag}<script src="${js}"></script></body></html>`;}
function metadataPanel(d){const rows=[['Code',d.code],['Type',d.type],['Status',d.status],['Owner',d.owner],['Route',d.route],['API',d.method&&d.apiPath?`${d.method} ${d.apiPath}`:null],['DB Object',d.objectName],['Updated',d.updatedAt],['Last reviewed',d.lastReviewedAt],['Source',d.relPath]].filter(([,v])=>v);return rows.length?`<div class="meta-grid">${rows.map(([k,v])=>`<div><span>${escapeHtml(k)}</span><strong>${escapeHtml(v)}</strong></div>`).join('')}</div>`:'';}
function relatedPanel(d,currentOut){if(!d.isEntity)return'';const cards=[];for(const e of graph.outbound.get(d.code)||[]){const t=byCode.get(e.to)?.[0];if(t)cards.push({d:t,label:e.relation,dir:'→'});}for(const e of graph.inbound.get(d.code)||[]){const t=byCode.get(e.from)?.[0];if(t)cards.push({d:t,label:e.relation,dir:'←'});}return `<section class="relations"><h2>Related documents</h2>${cards.length?`<div class="relation-grid">${cards.map(x=>`<a class="relation-card" href="${hrefFromOutput(currentOut,outputFileFor(x.d))}"><span>${x.dir} ${escapeHtml(x.label)}</span><strong>${escapeHtml(x.d.code)}</strong><small>${escapeHtml(x.d.title)}</small></a>`).join('')}</div>`:'<p class="muted">No relations declared.</p>'}</section>`;}
for(const d of docs){const out=outputFileFor(d),abs=path.join(siteDir,out);await ensureDir(path.dirname(abs));const body=`${metadataPanel(d)}<article class="markdown-body">${renderMarkdown(d.content,d,out)}</article>${relatedPanel(d,out)}<div class="source-ref">Source: ${escapeHtml(d.relPath)}</div>`;await fs.writeFile(abs,baseLayout({title:d.title,currentOut:out,body,subtitle:d.code?`${d.code} · ${d.type||''}`:d.section}),'utf8');}
const byType=new Map();for(const d of entities){if(!byType.has(d.type))byType.set(d.type,[]);byType.get(d.type).push(d);}const orphans=entities.filter(d=>d.type!=='module'&&!(graph.inbound.get(d.code)?.length)&&!(graph.outbound.get(d.code)?.length));const diagramCount=docs.reduce((n,d)=>n+d.mermaid.length,0);
const dashboard=`<section class="stats"><div><strong>${docs.length}</strong><span>Markdown docs</span></div><div><strong>${entities.length}</strong><span>Entity docs</span></div><div><strong>${graph.edges.length}</strong><span>Relations</span></div><div><strong>${diagramCount}</strong><span>Diagrams</span></div><div><strong>${orphans.length}</strong><span>Orphans</span></div></section><section class="dashboard-grid"><div class="panel"><h2>Entity inventory</h2><div class="bar-list">${[...byType.entries()].sort().map(([k,v])=>`<a href="catalog.html#type-${escapeHtml(k)}"><span>${escapeHtml(k)}</span><b>${v.length}</b></a>`).join('')}</div></div><div class="panel"><h2>Documentation pipeline</h2><ol class="workflow"><li>Edit canonical Markdown</li><li>Validate metadata & references</li><li>Sync catalog/traceability</li><li>Build static website</li><li>Review graph & diagrams</li></ol></div></section><section class="panel"><h2>Visual views</h2><div class="quick-grid"><a href="catalog.html"><strong>Catalog</strong><span>Entity inventory</span></a><a href="traceability.html"><strong>Traceability</strong><span>Feature relationship matrix</span></a><a href="graph.html"><strong>Interactive graph</strong><span>Visual project knowledge graph</span></a><a href="flows.html"><strong>Diagram gallery</strong><span>Mermaid flow/sequence/state/ERD</span></a></div></section>`;
await fs.writeFile(path.join(siteDir,'index.html'),baseLayout({title:config.projectName,currentOut:'index.html',body:dashboard,subtitle:'Documentation dashboard'}),'utf8');
let catalog='';for(const [type,items] of [...byType.entries()].sort()){catalog+=`<section class="panel" id="type-${escapeHtml(type)}"><h2>${escapeHtml(type)} <span class="count">${items.length}</span></h2><div class="table-wrap"><table><thead><tr><th>Code</th><th>Title</th><th>Status</th><th>Owner</th><th>Route / Endpoint / Object</th></tr></thead><tbody>${items.sort((a,b)=>a.code.localeCompare(b.code)).map(d=>`<tr><td><a href="${hrefFromOutput('catalog.html',outputFileFor(d))}">${escapeHtml(d.code)}</a></td><td>${escapeHtml(d.title)}</td><td>${escapeHtml(d.status||'')}</td><td>${escapeHtml(d.owner||'')}</td><td>${escapeHtml(d.route||(d.method&&d.apiPath?`${d.method} ${d.apiPath}`:d.objectName||''))}</td></tr>`).join('')}</tbody></table></div></section>`;}
await fs.writeFile(path.join(siteDir,'catalog.html'),baseLayout({title:'Document Catalog',currentOut:'catalog.html',body:catalog,subtitle:'Canonical entity inventory'}),'utf8');
function neighborhood(f){const seen=new Set([f.code]);let frontier=[f.code];for(let dep=0;dep<2;dep++){const next=[];for(const c of frontier)for(const e of graph.edges){const n=e.from===c?e.to:e.to===c?e.from:null;if(n&&!seen.has(n)){seen.add(n);next.push(n);}}frontier=next;}seen.delete(f.code);return[...seen].map(c=>byCode.get(c)?.[0]).filter(Boolean);}
const traceRows=entities.filter(d=>d.type==='feature').sort((a,b)=>a.code.localeCompare(b.code)).map(f=>{const groups={};for(const d of neighborhood(f)){(groups[d.type]??=[]).push(d);}const cell=(types)=>types.flatMap(t=>groups[t]||[]).map(d=>`<a class="pill" href="${hrefFromOutput('traceability.html',outputFileFor(d))}">${escapeHtml(d.code)}</a>`).join('')||'<span class="missing">—</span>';return`<tr><td><a href="${hrefFromOutput('traceability.html',outputFileFor(f))}">${escapeHtml(f.code)}</a><br><small>${escapeHtml(f.title)}</small></td><td>${cell(['requirement'])}</td><td>${cell(['business-rule'])}</td><td>${cell(['screen'])}</td><td>${cell(['api'])}</td><td>${cell(['database-object'])}</td><td>${cell(['test-case','test-script'])}</td><td>${cell(['decision'])}</td></tr>`;}).join('');
await fs.writeFile(path.join(siteDir,'traceability.html'),baseLayout({title:'Traceability Matrix',currentOut:'traceability.html',subtitle:'Two-hop feature relationship view',body:`<section class="panel"><div class="table-wrap"><table class="trace-table"><thead><tr><th>Feature</th><th>Requirements</th><th>Rules</th><th>Screens</th><th>APIs</th><th>DB</th><th>Tests</th><th>Decisions</th></tr></thead><tbody>${traceRows||'<tr><td colspan="8">No feature entities yet.</td></tr>'}</tbody></table></div></section>`}),'utf8');
const graphData=JSON.stringify({nodes:entities.map(d=>({id:d.code,label:d.code,title:d.title,type:d.type,status:d.status||'',href:hrefFromOutput('graph.html',outputFileFor(d))})),edges:graph.edges}).replaceAll('<','\\u003c');
await fs.writeFile(path.join(siteDir,'graph.html'),baseLayout({title:'Interactive Project Graph',currentOut:'graph.html',subtitle:'Pan, zoom, filter and click nodes to open documents',extraClass:'graph-page',body:`<section class="graph-toolbar"><input id="graphSearch" placeholder="Find code/title…"><select id="graphType"><option value="">All types</option>${[...new Set(entities.map(d=>d.type))].sort().map(t=>`<option>${escapeHtml(t)}</option>`).join('')}</select><button id="graphFit">Fit</button><span>${entities.length} nodes · ${graph.edges.length} edges</span></section><div id="projectGraph" class="project-graph"></div><script id="graphData" type="application/json">${graphData}</script>`}),'utf8');
const diagramDocs=docs.filter(d=>d.mermaid.length);const flowBody=diagramDocs.length?diagramDocs.map(d=>`<section class="panel diagram-card"><div class="diagram-card-head"><div><strong>${escapeHtml(d.code||d.title)}</strong><span>${escapeHtml(d.relPath)}</span></div><a href="${hrefFromOutput('flows.html',outputFileFor(d))}">Open document →</a></div><pre class="mermaid">${escapeHtml(d.mermaid[0])}</pre>${d.mermaid.length>1?`<small>+ ${d.mermaid.length-1} more diagram(s)</small>`:''}</section>`).join(''):'<section class="panel"><p>No Mermaid diagrams found.</p></section>';
await fs.writeFile(path.join(siteDir,'flows.html'),baseLayout({title:'Diagram Gallery',currentOut:'flows.html',subtitle:'Flowchart, sequence, state, ERD and architecture diagrams',body:flowBody}),'utf8');
const searchIndex=docs.map(d=>({title:d.title,code:d.code||'',type:d.type||'',section:d.section,path:d.relPath,href:hrefFromOutput('index.html',outputFileFor(d)),text:d.content.replace(/```[\s\S]*?```/g,' ').replace(/[#>*_`|\[\]()!-]/g,' ').replace(/\s+/g,' ').slice(0,12000)}));await fs.writeFile(path.join(siteDir,'search-index.json'),JSON.stringify(searchIndex),'utf8');
await fs.copyFile(path.join(projectRoot,'tools','assets','site.css'),path.join(siteDir,'assets','site.css'));await fs.copyFile(path.join(projectRoot,'tools','assets','site.js'),path.join(siteDir,'assets','site.js'));
console.log(`Built static documentation site: ${posix(path.relative(projectRoot,siteDir))}/index.html`);console.log(`Pages: ${docs.length+5}, diagrams: ${diagramCount}, graph: ${entities.length} nodes / ${graph.edges.length} edges.`);
