import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { ROOT, loadJson, writeJson, ensureDir, scanEntities, markdownFiles, parseFrontmatter, rel, slugPath, escapeHtml, renderMarkdown, resolveStandards, walk, workspaceAbs, workspaceRel } from '../lib/common.mjs';
import { freshnessSummary } from '../lib/freshness.mjs';
import { listJsonRecords, changesetDir, baselineDir } from '../lib/change-history.mjs';
import { allSpecSummaries, resolveSpec } from '../lib/specification.mjs';
import { entityPolicy, isUuid, resolveRelationMapping } from '../lib/model-governance.mjs';
import { buildVerificationReport, verificationFindings } from '../lib/verification.mjs';
import { blueprintStatus } from '../lib/blueprint-projection.mjs';

const cmd=process.argv[2]||'help';
const profile=loadJson('project.profile.json',{});
const registry=loadJson('registry/entity-types.json',{types:{}});
const relationMap=loadJson('registry/relation-map.json',{relations:[]});
const quality=loadJson('registry/quality-rules.json',{rules:[]});
const starterKit=loadJson('starter-kit.json',{});

function issue(level,code,message,file=''){return {level,code,message,file};}
function validate(){
  const issues=[]; const {entities}=scanEntities(); const byCode=new Map(); const byUid=new Map(); const modelPolicy=entityPolicy();
  const layout=starterKit.documentationLayout||{};
  const historyDir=layout.historyDirectory;
  if(historyDir && !fs.existsSync(path.join(ROOT,historyDir))) issues.push(issue('error','HISTORY_DIR_MISSING',`Configured history directory ${historyDir} does not exist`,'starter-kit.json'));
  const historyPatterns=[];
  for(const raw of layout.rootHistoryPatterns||[]){ try{historyPatterns.push(new RegExp(raw));}catch{issues.push(issue('error','HISTORY_PATTERN_INVALID',`Invalid root history pattern ${raw}`,'starter-kit.json'));} }
  for(const entry of fs.readdirSync(ROOT,{withFileTypes:true})){ if(!entry.isFile()||!entry.name.endsWith('.md'))continue; if(historyPatterns.some(r=>r.test(entry.name))) issues.push(issue('error','ROOT_HISTORY_DOC',`${entry.name} is historical release/upgrade material; move it to ${historyDir||'docs/history'}`,entry.name)); }
  const pts=loadJson('registry/project-types.json',{projectTypes:{}}).projectTypes;
  const stacks=loadJson('registry/technology-stacks.json',{stacks:{}}).stacks;
  for(const t of profile.projectTypes||[]) if(!pts[t]) issues.push(issue('error','PROFILE_TYPE',`Unknown project type ${t}`,'project.profile.json'));
  for(const s of profile.technologyStacks||[]){ if(!stacks[s]) issues.push(issue('error','PROFILE_STACK',`Unknown technology stack ${s}`,'project.profile.json')); else if((profile.projectTypes||[]).length && !(stacks[s].projectTypes||[]).some(x=>(profile.projectTypes||[]).includes(x)) && s!=='postgresql') issues.push(issue('warning','PROFILE_COMPAT',`Stack ${s} is not mapped to selected project types`,'project.profile.json')); }
  const specCfg=loadJson('registry/spec-profiles.json',{levels:[],maturities:[]});
  const requestedDefault=profile.documentation?.defaultSpecLevel; if(requestedDefault && ![...(specCfg.levels||[]),'auto'].includes(requestedDefault)) issues.push(issue('error','PROFILE_SPEC_LEVEL',`Unknown defaultSpecLevel ${requestedDefault}`,'project.profile.json'));
  const maturity=profile.documentation?.targetMaturity; if(maturity && !(specCfg.maturities||[]).includes(maturity)) issues.push(issue('error','PROFILE_MATURITY',`Unknown targetMaturity ${maturity}`,'project.profile.json'));
  const escalation=profile.documentation?.riskEscalation; if(escalation && !['warn','block','off'].includes(escalation)) issues.push(issue('error','PROFILE_RISK_ESCALATION',`Unknown riskEscalation ${escalation}`,'project.profile.json'));
  const bpCfg=loadJson('registry/blueprint-profiles.json',{profiles:{},audiences:{}});
  if(profile.blueprint?.defaultProfile && !bpCfg.profiles?.[profile.blueprint.defaultProfile]) issues.push(issue('error','PROFILE_BLUEPRINT_LEVEL',`Unknown blueprint.defaultProfile ${profile.blueprint.defaultProfile}`,'project.profile.json'));
  if(profile.blueprint?.defaultAudience && !bpCfg.audiences?.[profile.blueprint.defaultAudience]) issues.push(issue('error','PROFILE_BLUEPRINT_AUDIENCE',`Unknown blueprint.defaultAudience ${profile.blueprint.defaultAudience}`,'project.profile.json'));
  if(profile.blueprint?.ownershipPolicy && profile.blueprint.ownershipPolicy!=='progressive') issues.push(issue('error','PROFILE_BLUEPRINT_OWNERSHIP',`Unknown blueprint.ownershipPolicy ${profile.blueprint.ownershipPolicy}`,'project.profile.json'));
  for(const e of entities){
    if(byCode.has(e.code)) issues.push(issue('error','DUPLICATE_CODE',`Duplicate code ${e.code}`,e.path)); else byCode.set(e.code,e);
    if (!e.uid) issues.push(issue(modelPolicy.identity?.legacyMissingUidSeverity || 'warning','MISSING_UID',`${e.code} has no permanent uid; run npm run entity:identity-backfill -- --apply`,e.path));
    else if (!isUuid(e.uid)) issues.push(issue('error','INVALID_UID',`${e.code}: uid is not a UUID`,e.path));
    else if (byUid.has(e.uid)) issues.push(issue('error','DUPLICATE_UID',`${e.code} duplicates uid used by ${byUid.get(e.uid).code}`,e.path));
    else byUid.set(e.uid,e);
    if (e.uid && (!Number.isFinite(e.revision) || e.revision < 1)) issues.push(issue('warning','MISSING_REVISION',`${e.code} has uid but no valid revision`,e.path));
    const def=registry.types[e.type]; if(!def) issues.push(issue('error','UNKNOWN_TYPE',`Unknown entity type ${e.type}`,e.path)); else if(e.status && !(def.statuses||[]).includes(e.status)) issues.push(issue('error','INVALID_STATUS',`${e.code}: status ${e.status} not allowed for ${e.type}`,e.path));
    if(!e.meta.title) issues.push(issue('warning','MISSING_TITLE',`${e.code} has no title`,e.path));
    if(e.type==='feature'){
      const specCfg=loadJson('registry/spec-profiles.json',{levels:[],maturities:[]});
      if(e.meta.spec_level && ![...(specCfg.levels||[]),'auto'].includes(String(e.meta.spec_level))) issues.push(issue('error','INVALID_SPEC_LEVEL',`${e.code}: invalid spec_level ${e.meta.spec_level}`,e.path));
      if(e.meta.target_maturity && !(specCfg.maturities||[]).includes(String(e.meta.target_maturity))) issues.push(issue('error','INVALID_TARGET_MATURITY',`${e.code}: invalid target_maturity ${e.meta.target_maturity}`,e.path));
    }
    if(e.type==='application'){
      const sourceCfg=loadJson('registry/source-profiles.json',{profiles:{}}); const sp=String(e.meta.source_profile||'');
      if(!sp || !sourceCfg.profiles?.[sp]) issues.push(issue('error','INVALID_SOURCE_PROFILE',`${e.code}: unknown source_profile ${sp||'(missing)'}`,e.path));
      if(!e.meta.source_root) issues.push(issue('error','SOURCE_ROOT_MISSING',`${e.code}: source_root is required`,e.path));
      else { const abs=path.resolve(ROOT,String(e.meta.source_root)); if(!(abs===ROOT||abs.startsWith(ROOT+path.sep))) issues.push(issue('error','SOURCE_ROOT_OUTSIDE',`${e.code}: source_root must stay inside project workspace`,e.path)); }
    }
    const degree=Object.values(e.meta.related||{}).filter(Array.isArray).reduce((n,a)=>n+a.length,0); if(degree>20) issues.push(issue('warning','OVER_LINK',`${e.code} has ${degree} outgoing related links; review for over-linking`,e.path));
  }
  for(const e of entities){
    const related=e.meta.related||{};
    for(const [field,vals0] of Object.entries(related)){
      const vals=Array.isArray(vals0)?vals0:(vals0?[vals0]:[]);
      const fieldMapping=resolveRelationMapping(e.type,field);
      if(!fieldMapping && vals.length){issues.push(issue('warning','UNMAPPED_RELATION',`${e.code}.${field} has no relation-map rule`,e.path));continue;}
      const max=fieldMapping?.max ?? (fieldMapping?.cardinality==='many-to-one'||fieldMapping?.cardinality==='one-to-one'?1:null);
      if(max!==null && max!==undefined && vals.length>Number(max)) issues.push(issue('error','CARDINALITY',`${e.code}.${field} allows at most ${max} target(s)`,e.path));
      for(const code of vals){
        const target=byCode.get(String(code)); const mapping=resolveRelationMapping(e.type,field,target?.type||null) || fieldMapping;
        if(!target){ if(!mapping?.allowUnresolved) issues.push(issue('error','BROKEN_RELATION',`${e.code}.${field} -> ${code} not found`,e.path)); else issues.push(issue('warning','UNRESOLVED_RELATION',`${e.code}.${field} -> ${code} is unresolved`,e.path)); continue; }
        if(!mapping){issues.push(issue('error','RELATION_TYPE',`${e.code}.${field} cannot target ${target.type} (${code})`,e.path));continue;}
        if(mapping.to!=='*'&&target.type!==mapping.to) issues.push(issue('error','RELATION_TYPE',`${e.code}.${field} expects ${mapping.to}, got ${target.type} (${code})`,e.path));
        if(mapping.fallback && modelPolicy.relations?.warnOnFallbackMappings) issues.push(issue('warning','BROAD_RELATION',`${e.code}.${field} -> ${code} uses fallback relation rule ${mapping.key||mapping.field}`,e.path));
      }
    }
    for(const mapping of relationMap.relations.filter(r=>!r.fallback&&r.from===e.type&&r.required)){ const vals=Array.isArray(related[mapping.field])?related[mapping.field]:[]; const min=Number(mapping.min||1); if(vals.length<min)issues.push(issue('error','REQUIRED_RELATION',`${e.code}.${mapping.field} requires at least ${min} target(s)`,e.path)); }
  }
  for(const rule of quality.rules||[]){
    if(rule.projectType && !(profile.projectTypes||[]).includes(rule.projectType)) continue;
    if(rule.type==='relation-min') for(const e of entities.filter(x=>x.type===rule.entityType&&(!(rule.statusIn||[]).length||(rule.statusIn||[]).includes(x.status)))){if(rule.minSpecLevel&&e.type==='feature'){const rank={lightweight:0,standard:1,full:2};const level=resolveSpec(e).effectiveLevel;if((rank[level]??1)<(rank[rule.minSpecLevel]??0))continue;}const n=Array.isArray(e.meta.related?.[rule.field])?e.meta.related[rule.field].length:0;if(n<rule.min)issues.push(issue(rule.severity,rule.id,`${e.code} requires at least ${rule.min} ${rule.field}`,e.path));}
    if(rule.type==='body-contains') for(const e of entities.filter(x=>x.type===rule.entityType)){const b=e.body.toLowerCase();const miss=(rule.terms||[]).filter(t=>!b.includes(String(t).toLowerCase()));if(miss.length)issues.push(issue(rule.severity,rule.id,`${e.code} missing documented terms: ${miss.join(', ')}`,e.path));}
    if(rule.type==='status') for(const e of entities.filter(x=>x.type===rule.entityType&&(rule.statusIn||[]).includes(x.status)))issues.push(issue(rule.severity,rule.id,`${e.code} is in blocking status ${e.status}`,e.path));
    if(rule.type==='pack-review-pending'&&profile.implementationGate?.blockOnPackReviewPending){const lock=loadJson('.project-docs/packs.lock.json',{packs:{}});for(const [id,p] of Object.entries(lock.packs||{}))if(p.reviewStatus!=='approved')issues.push(issue(rule.severity,rule.id,`Pack ${id}@${p.version} review is ${p.reviewStatus||'pending'}`,'.project-docs/packs.lock.json'));}
    if(rule.type==='freshness-stale'&&profile.implementationGate?.blockOnStaleDocumentation){for(const item of freshnessSummary().filter(x=>x.status==='stale'))issues.push(issue(rule.severity,rule.id,`${item.code} is stale because dependencies changed: ${(item.changedDependencies||[]).join(', ')}`,'.project-docs/freshness'));}
  }
  const verification=verificationFindings(entities,quality.rules||[]);
  for(const finding of verification.findings) issues.push(issue(finding.severity,finding.code,finding.message,finding.file));
  writeJson('.project-docs/reports/verification-report.json',{...verification.report,findings:verification.findings});
  const errors=issues.filter(x=>x.level==='error').length, warnings=issues.filter(x=>x.level==='warning').length;
  console.log(`Validation: ${errors} error(s), ${warnings} warning(s)`); for(const i of issues) console.log(`[${i.level.toUpperCase()}] ${i.code}: ${i.message}${i.file?' ('+i.file+')':''}`);
  writeJson('docs/_generated/validation-report.json',{generatedAt:new Date().toISOString(),summary:{errors,warnings},issues});
  return errors===0;
}
function sync(){
  const {docs,entities}=scanEntities(); const byCode=new Map(entities.map(e=>[e.code,e])); const verification=buildVerificationReport(entities); const verificationByRequirement=new Map((verification.requirements||[]).map(x=>[x.code,x])); const edges=[];
  for(const e of entities) for(const [field,vals0] of Object.entries(e.meta.related||{})) for(const target of (Array.isArray(vals0)?vals0:[])) if(byCode.has(String(target))){ const targetEntity=byCode.get(String(target)); const mapping=resolveRelationMapping(e.type,field,targetEntity.type); edges.push({from:e.code,to:String(target),fromUid:e.uid||null,toUid:targetEntity.uid||null,field,relation:mapping?.relation||field,reverse:mapping?.reverse||null,fallback:Boolean(mapping?.fallback)}); }
  const rows=entities.filter(e=>e.type==='feature').map(f=>{
    const direct=(field)=>Array.isArray(f.meta.related?.[field])?f.meta.related[field]:[];
    const reqs=direct('requirements'); const reqTests=reqs.flatMap(c=>Array.isArray(byCode.get(c)?.meta.related?.tests)?byCode.get(c).meta.related.tests:[]);
    const incomingTasks=entities.filter(e=>e.type==='task'&&Array.isArray(e.meta.related?.features)&&e.meta.related.features.includes(f.code)).map(e=>e.code); const acTotal=reqs.reduce((n,c)=>n+(verificationByRequirement.get(c)?.acceptanceTotal||0),0); const acCovered=reqs.reduce((n,c)=>n+(verificationByRequirement.get(c)?.acceptanceCovered||0),0); return {feature:f.code,applications:direct('applications'),module:direct('modules'),requirements:reqs,acceptance:{covered:acCovered,total:acTotal,coverage:acTotal?Math.round(acCovered*100/acTotal):100},rules:direct('business_rules'),screens:direct('screens'),apis:direct('apis'),database:direct('database_objects'),permissions:direct('permissions'),deepLinks:direct('deep_links'),tests:[...new Set([...direct('tests'),...reqTests])],tasks:incomingTasks};
  });
  const installed=loadJson('.project-docs/packs.lock.json',{packs:{}}); const libraries=listPackLibraries();
  ensureDir(path.join(ROOT,'docs/_generated'));
  writeJson('docs/_generated/catalog.json',{generatedAt:new Date().toISOString(),documents:docs.map(d=>({path:d.path,title:d.title,uid:d.meta.uid||null,code:d.meta.code||null,revision:Number(d.meta.revision||0),type:d.meta.type||null,status:d.meta.status||null})),entities:entities.map(e=>({path:e.path,title:e.title,uid:e.uid||null,code:e.code,revision:e.revision||0,type:e.type,status:e.status,specLevel:e.type==='feature'?resolveSpec(e).effectiveLevel:null,targetMaturity:e.type==='feature'?resolveSpec(e).targetMaturity:null}))});
  writeJson('docs/_generated/graph.json',{nodes:entities.map(e=>({id:e.code,uid:e.uid||null,label:e.title,type:e.type,path:e.path,revision:e.revision||0})),edges});
  writeJson('docs/_generated/traceability.json',{rows}); writeJson('docs/_generated/reuse.json',{installed:installed.packs||{},libraries});
  writeJson('docs/_generated/verification.json',verification); writeJson('.project-docs/reports/verification-report.json',verification);
  const sourceLock=loadJson('.project-docs/source.lock.json',{schemaVersion:'1.0',applications:{}}); const sourceProfiles=loadJson('registry/source-profiles.json',{profiles:{}}); const appEntities=entities.filter(e=>e.type==='application').map(e=>({code:e.code,title:e.title,status:e.status,path:e.path,applicationType:e.meta.application_type||null,sourceProfile:e.meta.source_profile||null,technologyStack:e.meta.technology_stack||null,sourceRoot:e.meta.source_root||null,sourceBase:e.meta.source_base||null,sourceBaseVersion:e.meta.source_base_version||null,sourceVariant:e.meta.source_variant||null,sourceOrigin:e.meta.source_origin||null,lock:sourceLock.applications?.[e.code]||null})); writeJson('docs/_generated/source-workspace.json',{generatedAt:new Date().toISOString(),applications:appEntities,profiles:sourceProfiles.profiles||{},lock:sourceLock});
  const workplanDir=path.join(ROOT,'.project-docs/workplans'); const workplans=fs.existsSync(workplanDir)?fs.readdirSync(workplanDir).filter(x=>x.endsWith('.json')).map(x=>JSON.parse(fs.readFileSync(path.join(workplanDir,x),'utf8'))):[];
  const freshness=freshnessSummary(); writeJson('docs/_generated/freshness.json',{generatedAt:new Date().toISOString(),items:freshness,summary:{fresh:freshness.filter(x=>x.status==='fresh').length,stale:freshness.filter(x=>x.status==='stale').length,selfChanged:freshness.filter(x=>x.status==='self_changed').length,untracked:freshness.filter(x=>x.status==='untracked').length}});
  const specification=allSpecSummaries(); writeJson('docs/_generated/specification.json',{generatedAt:new Date().toISOString(),features:specification,summary:{lightweight:specification.filter(x=>x.effectiveLevel==='lightweight').length,standard:specification.filter(x=>x.effectiveLevel==='standard').length,full:specification.filter(x=>x.effectiveLevel==='full').length,belowRecommended:specification.filter(x=>x.belowRecommended).length}});
  const changesets=listJsonRecords(changesetDir()); const baselines=listJsonRecords(baselineDir());
  writeJson('docs/_generated/governance.json',{generatedAt:new Date().toISOString(),applications:appEntities,requests:entities.filter(e=>e.type==='request').map(e=>({code:e.code,title:e.title,status:e.status,path:e.path})),tasks:entities.filter(e=>e.type==='task').map(e=>({code:e.code,title:e.title,status:e.status,path:e.path,workplanId:e.meta.workplan_id||null})),bugs:entities.filter(e=>e.type==='bug').map(e=>({code:e.code,title:e.title,status:e.status,path:e.path})),workplans:workplans.map(w=>({id:w.id,title:w.title,status:w.status,featureCode:w.featureCode,specLevel:w.specLevel||w.context?.feature?.specLevel||null,targetMaturity:w.targetMaturity||w.context?.feature?.targetMaturity||null,requiresAuthoring:w.requiresAuthoring,materializedTaskCodes:w.materializedTaskCodes||[]})),freshness,changesets:changesets.map(x=>({id:x.id,createdAt:x.createdAt,actor:x.actor,reason:x.reason,summary:x.summary})),baselines:baselines.map(x=>({id:x.id,name:x.name,createdAt:x.createdAt,actor:x.actor,note:x.note,summary:x.summary}))});
  fs.writeFileSync(path.join(ROOT,'docs/_generated/DOCUMENT_INDEX.md'),'# Document Index\n\n'+docs.map(d=>`- [${d.title}](../../${d.path})`).join('\n')+'\n');
  fs.writeFileSync(path.join(ROOT,'docs/_generated/TRACEABILITY_MATRIX.md'),'# Traceability Matrix\n\n| Feature | Applications | Module | Requirements | Acceptance | Screens | APIs | Tests | Tasks |\n|---|---|---|---|---|---|---|---|---|\n'+rows.map(r=>`| ${r.feature} | ${(r.applications||[]).join(', ')} | ${r.module.join(', ')} | ${r.requirements.join(', ')} | ${r.acceptance.covered}/${r.acceptance.total} (${r.acceptance.coverage}%) | ${r.screens.join(', ')} | ${r.apis.join(', ')} | ${r.tests.join(', ')} | ${r.tasks.join(', ')} |`).join('\n')+'\n');
  console.log(`Synced ${docs.length} markdown files, ${entities.length} entities, ${edges.length} typed edges.`);
}
function listPackLibraries(){
  const result=[]; for(const key of ['reuse.capabilities','reuse.patterns']){const abs=workspaceAbs(key);if(!fs.existsSync(abs))continue;for(const name of fs.readdirSync(abs)){const m=path.join(abs,name,'manifest.json');if(fs.existsSync(m)){const j=JSON.parse(fs.readFileSync(m,'utf8'));result.push({packageId:j.packageId,packageType:j.packageType,version:j.version,path:workspaceRel(key,name)});}}} return result;
}
function shell(title,body,active='',base=''){ const nav=[['index.html','Dashboard'],['profile.html','Profile'],['standards.html','Standards'],['source.html','Source'],['blueprint.html','Blueprint'],['brownfield.html','Brownfield'],['mockups.html','Mockups'],['packs.html','Reuse'],['catalog.html','Catalog'],['traceability.html','Traceability'],['verification.html','Verification'],['graph.html','Graph'],['governance.html','Governance'],['specification.html','Spec Levels'],['flows.html','Diagrams']];return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><link rel="stylesheet" href="${base}assets/style.css"></head><body><header><strong>Project Docs v5.10</strong><nav>${nav.map(([u,l])=>`<a class="${active===u?'active':''}" href="${base}${u}">${l}</a>`).join('')}</nav></header><main><h1>${escapeHtml(title)}</h1>${body}</main><script src="assets/app.js"></script><script type="module">if(document.querySelector('.mermaid')){import('https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs').then(m=>{m.default.initialize({startOnLoad:true,securityLevel:'loose'});});}</script></body></html>`; }
function build(){
  sync(); const site=workspaceAbs('site'); fs.rmSync(site,{recursive:true,force:true}); ensureDir(path.join(site,'pages')); ensureDir(path.join(site,'assets'));
  fs.writeFileSync(path.join(site,'assets/style.css'),`body{margin:0;font:15px system-ui,sans-serif;background:#f7f7f8;color:#1d1d1f}header{position:sticky;top:0;background:#fff;border-bottom:1px solid #ddd;padding:12px 20px;display:flex;gap:24px;align-items:center;z-index:10}nav{display:flex;gap:10px;flex-wrap:wrap}nav a{color:#444;text-decoration:none;padding:6px 9px;border-radius:8px}nav a.active,nav a:hover{background:#eee}main{max-width:1200px;margin:0 auto;padding:24px}.card{background:#fff;border:1px solid #ddd;border-radius:12px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}table{border-collapse:collapse;width:100%;background:#fff}th,td{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:top}pre{overflow:auto;background:#171717;color:#f5f5f5;padding:14px;border-radius:10px}code{background:#eee;padding:1px 4px;border-radius:4px}pre code{background:transparent}a{color:#0957d0}.badge{display:inline-block;padding:2px 7px;border-radius:999px;background:#eee;margin:2px}.search{width:100%;padding:10px;border:1px solid #bbb;border-radius:9px}svg{background:#fff;border:1px solid #ddd;border-radius:12px}`);
  fs.writeFileSync(path.join(site,'assets/app.js'),`document.querySelectorAll('[data-search]').forEach(i=>i.addEventListener('input',()=>{const q=i.value.toLowerCase();document.querySelectorAll('[data-search-item]').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'':'none')}));`);
  const catalog=loadJson('docs/_generated/catalog.json',{documents:[],entities:[]}); const mockups=loadJson('.project-docs/mockups/report.json',{pass:true,summary:{assets:0,mapped:0,unmapped:0,needsAnalysis:0,findings:0,functionalCovered:0},assets:[],findings:[]}); const trace=loadJson('docs/_generated/traceability.json',{rows:[]}); const verification=loadJson('docs/_generated/verification.json',{summary:{acceptanceCriteria:0,acceptanceCovered:0,acceptanceCoverage:100,criticalBusinessRules:0,criticalRulesFullyCovered:0},requirements:[],businessRules:[]}); const graph=loadJson('docs/_generated/graph.json',{nodes:[],edges:[]}); const reuse=loadJson('docs/_generated/reuse.json',{libraries:[],installed:{}}); const governance=loadJson('docs/_generated/governance.json',{requests:[],tasks:[],bugs:[],workplans:[],freshness:[],changesets:[],baselines:[]}); const specification=loadJson('docs/_generated/specification.json',{features:[],summary:{lightweight:0,standard:0,full:0,belowRecommended:0}}); const sourceWorkspace=loadJson('docs/_generated/source-workspace.json',{applications:[],profiles:{},lock:{applications:{}}});
  const standards=resolveStandards(profile);
  const blueprint=blueprintStatus();
  const staleCount=(governance.freshness||[]).filter(x=>x.status==='stale').length;
  const cards=`<div class="grid"><div class="card"><b>${catalog.documents.length}</b><br>Markdown documents</div><div class="card"><b>${catalog.entities.length}</b><br>Typed entities</div><div class="card"><b>${sourceWorkspace.applications.length}</b><br>Applications</div><div class="card"><b>${graph.edges.length}</b><br>Relations</div><div class="card"><b>${reuse.libraries.length}</b><br>Reusable packs</div><div class="card"><b>${governance.requests.length}</b><br>Requests</div><div class="card"><b>${governance.tasks.length}</b><br>Tasks</div><div class="card"><b>${governance.workplans.length}</b><br>WorkPlans</div><div class="card"><b>${staleCount}</b><br>Stale docs</div><div class="card"><b>${governance.changesets.length}</b><br>ChangeSets</div><div class="card"><b>${governance.baselines.length}</b><br>Baselines</div><div class="card"><b>${specification.summary.lightweight||0}</b><br>Lightweight specs</div><div class="card"><b>${specification.summary.belowRecommended||0}</b><br>Spec escalation warnings</div></div><div class="card"><input class="search" data-search placeholder="Filter quick links"><div data-search-item><a href="profile.html">Project profile and selected standards</a></div><div data-search-item><a href="source.html">Application boundaries, source profiles and Source Base provenance</a></div><div data-search-item><a href="blueprint.html">Progressive Blueprint ownership, projections and conflicts</a></div><div data-search-item><a href="brownfield.html">Existing-source inventory, candidate review and baseline reconciliation</a></div><div data-search-item><a href="mockups.html">Mockup image inventory, Screen mapping, functional coverage and drift</a></div><div data-search-item><a href="packs.html">Capability/Pattern Pack library and installed packs</a></div><div data-search-item><a href="traceability.html">Typed feature traceability</a></div><div data-search-item><a href="verification.html">Acceptance Criteria and Business Rule verification coverage</a></div><div data-search-item><a href="graph.html">Project knowledge graph</a></div><div data-search-item><a href="governance.html">Request, WorkPlan, freshness, ChangeSet and baseline governance</a></div><div data-search-item><a href="specification.html">Progressive specification levels and maturity</a></div></div>`;
  fs.writeFileSync(path.join(site,'index.html'),shell('Documentation Dashboard',cards,'index.html'));
  fs.writeFileSync(path.join(site,'profile.html'),shell('Project Profile',`<pre>${escapeHtml(JSON.stringify(profile,null,2))}</pre><h2>Applicable standards</h2>${standards.map(s=>`<div class="card"><span class="badge">${escapeHtml(s.layer)}</span> ${escapeHtml(s.path)}</div>`).join('')}`,'profile.html'));
  fs.writeFileSync(path.join(site,'standards.html'),shell('Applicable Standards',standards.map(s=>`<div class="card"><b>${escapeHtml(s.layer)}</b><br>${escapeHtml(s.path)}</div>`).join(''),'standards.html'));
  const mockupRows=(mockups.assets||[]).map(a=>`<tr><td><code>${escapeHtml(a.path)}</code></td><td>${escapeHtml(a.classification||'')}</td><td>${escapeHtml(a.analysisStatus||'')}</td><td>${escapeHtml((a.screens||[]).join(', ')||'—')}</td><td>${escapeHtml((a.functionalCoverage?.features||[]).join(', ')||'—')}</td><td>${escapeHtml((a.functionalCoverage?.requirements||[]).join(', ')||'—')}</td><td>${escapeHtml((a.functionalCoverage?.flows||[]).join(', ')||'—')}</td><td>${escapeHtml((a.functionalCoverage?.tests||[]).join(', ')||'—')}</td></tr>`).join(''); const mockupFindings=(mockups.findings||[]).map(f=>`<div class="card"><b>${escapeHtml(String(f.severity||'').toUpperCase())} ${escapeHtml(f.code||'')}</b><br>${escapeHtml(f.message||'')}</div>`).join(''); const mockupHtml=`<div class="grid"><div class="card"><b>${mockups.summary?.assets||0}</b><br>Mockup assets</div><div class="card"><b>${mockups.summary?.mapped||0}</b><br>Mapped to Screens</div><div class="card"><b>${mockups.summary?.functionalCovered||0}</b><br>Feature-owned coverage</div><div class="card"><b>${mockups.summary?.needsAnalysis||0}</b><br>Need vision analysis</div><div class="card"><b>${mockups.summary?.findings||0}</b><br>Findings</div></div><p>Mockups are design evidence. Canonical behaviour remains in Screen/Feature/Requirement/Rule/API/DB/Test documents.</p><h2>Coverage</h2><table><tr><th>Mockup</th><th>Class</th><th>Analysis</th><th>Screen</th><th>Feature</th><th>Requirement</th><th>Flow</th><th>Test</th></tr>${mockupRows||'<tr><td colspan="8">No mockup assets yet.</td></tr>'}</table><h2>Findings</h2>${mockupFindings||'<p>No mockup findings.</p>'}`; fs.writeFileSync(path.join(site,'mockups.html'),shell('Mockup Coverage',mockupHtml,'mockups.html'));
  const sourceRows=(sourceWorkspace.applications||[]).map(a=>`<tr><td>${escapeHtml(a.code)}</td><td>${escapeHtml(a.applicationType||'')}</td><td>${escapeHtml(a.sourceProfile||'')}</td><td>${escapeHtml(a.technologyStack||'')}</td><td><code>${escapeHtml(a.sourceRoot||'')}</code></td><td>${escapeHtml(a.lock?.origin||a.sourceOrigin||'')}</td><td>${a.lock?.sourceBase?escapeHtml(`${a.lock.sourceBase.id}@${a.lock.sourceBase.version}/${a.lock.variant||''}`):'—'}</td></tr>`).join(''); const sourceHtml=`<div class="grid"><div class="card"><b>${sourceWorkspace.applications.length}</b><br>Application boundaries</div><div class="card"><b>${Object.keys(sourceWorkspace.profiles||{}).length}</b><br>Source profiles</div></div><h2>Applications</h2>${sourceRows?`<table><tr><th>Application</th><th>Type</th><th>Profile</th><th>Stack</th><th>Root</th><th>Origin</th><th>Source Base</th></tr>${sourceRows}</table>`:'<p>No applications configured. Use <code>source:init</code> or <code>source:adopt</code>.</p>'}<h2>Profiles</h2>${Object.entries(sourceWorkspace.profiles||{}).map(([id,p])=>`<div class="card"><b>${escapeHtml(id)}</b> <span class="badge">${escapeHtml(p.applicationType)}</span> <span class="badge">${escapeHtml(p.technologyStack)}</span><br>Default root: <code>${escapeHtml(p.defaultRoot)}</code> · Base: ${escapeHtml(p.sourceBase||'adopt existing')}</div>`).join('')}`; fs.writeFileSync(path.join(site,'source.html'),shell('Source Workspace',sourceHtml,'source.html'));
  const bpHtml=`<div class="grid"><div class="card"><b>${blueprint.summary.inline||0}</b><br>Inline-owned items</div><div class="card"><b>${blueprint.summary.linked||0}</b><br>Linked canonical items</div><div class="card"><b>${blueprint.summary.generated||0}</b><br>Rendered projections</div><div class="card"><b>${blueprint.summary.pendingCandidates||0}</b><br>Pending candidates</div><div class="card"><b>${blueprint.summary.stale||0}</b><br>Stale projections</div><div class="card"><b>${blueprint.summary.conflicts||0}</b><br>Ownership conflicts</div></div><h2>Progressive ownership</h2><p>Inline Blueprint seeds are canonical until reviewed promotion. After promotion, the linked document under <code>docs/</code> owns the detail and Blueprint summaries are generated projections.</p><h2>Diff status</h2>${(blueprint.diff||[]).map(x=>`<div class="card"><b>${escapeHtml(x.code)}</b> <span class="badge">${escapeHtml(x.ownership)}</span> <span class="badge">${escapeHtml(x.status)}</span><br>${escapeHtml((x.details||[]).join('; ')||'In sync')}</div>`).join('')||'<p>No Blueprint-owned items yet.</p>'}<h2>Commands</h2><pre>blueprint:expand -> review -> blueprint:promote -> blueprint:compile / blueprint:render
blueprint:diff -> blueprint:reconcile -- --prefer linked</pre>`;
  fs.writeFileSync(path.join(site,'blueprint.html'),shell('Blueprint Projection',bpHtml,'blueprint.html'));
  const bfInventory=loadJson('.project-docs/brownfield/inventory.json',null); const bfCandidates=loadJson('.project-docs/brownfield/candidates.json',null); const bfReconciliation=loadJson('.project-docs/brownfield/reconciliation.json',null); const bfPlan=loadJson('.project-docs/brownfield/refactor-plan.json',null); const adoption=profile.adoption||{mode:'greenfield',baselineStatus:'not-required'}; const bfHtml=`<div class="grid"><div class="card"><b>${escapeHtml(adoption.mode||'greenfield')}</b><br>Adoption mode</div><div class="card"><b>${escapeHtml(adoption.baselineStatus||'not-required')}</b><br>Baseline status</div><div class="card"><b>${bfInventory?.summary?.files||0}</b><br>Inventoried files</div><div class="card"><b>${bfCandidates?.summary?.total||0}</b><br>Candidates</div><div class="card"><b>${bfCandidates?.summary?.pending||0}</b><br>Pending review</div><div class="card"><b>${bfReconciliation?(bfReconciliation.pass?'PASS':'FAIL'):'—'}</b><br>Reconciliation</div></div><h2>Safety model</h2><p>Inventory and candidates are derived evidence. Canonical docs are created only after explicit review and promotion. Refactor planning never moves source automatically.</p><h2>Reconciliation findings</h2>${(bfReconciliation?.findings||[]).map(f=>`<div class="card"><b>${escapeHtml(f.code)}</b> <span class="badge">${escapeHtml(f.severity)}</span><br>${escapeHtml(f.message)}</div>`).join('')||'<p>No reconciliation report yet.</p>'}<h2>Normalization proposal</h2>${bfPlan?`<pre>${escapeHtml(JSON.stringify(bfPlan.moves||[],null,2))}</pre>`:'<p>No refactor plan generated.</p>'}`; fs.writeFileSync(path.join(site,'brownfield.html'),shell('Brownfield Adoption',bfHtml,'brownfield.html'));
  const packHtml=`<h2>Library</h2>${reuse.libraries.map(p=>`<div class="card"><b>${escapeHtml(p.packageId)}</b> <span class="badge">${escapeHtml(p.packageType)}</span> <span class="badge">${escapeHtml(p.version)}</span><br>${escapeHtml(p.path)}</div>`).join('')}<h2>Installed</h2>${Object.keys(reuse.installed).length?Object.entries(reuse.installed).map(([id,p])=>`<div class="card"><b>${escapeHtml(id)}@${escapeHtml(p.version)}</b> <span class="badge">${escapeHtml(p.reviewStatus||'pending')}</span><br>Features: ${escapeHtml((p.features||[]).join(', '))}</div>`).join(''):'<p>No packs imported into this starter workspace.</p>'}`;
  fs.writeFileSync(path.join(site,'packs.html'),shell('Reuse Library',packHtml,'packs.html'));
  fs.writeFileSync(path.join(site,'catalog.html'),shell('Document Catalog',`<input class="search" data-search placeholder="Filter documents">${catalog.documents.map(d=>`<div class="card" data-search-item><a href="pages/${slugPath(d.path)}">${escapeHtml(d.title)}</a>${d.code?` <span class="badge">${escapeHtml(d.code)}</span>`:''}<br><small>${escapeHtml(d.path)}</small></div>`).join('')}`,'catalog.html'));
  const headers=['Feature','Applications','Module','Requirements','Acceptance','Rules','Screens','APIs','DB','Permissions','Deep Links','Tests','Tasks']; const rowHtml=trace.rows.map(r=>`<tr><td>${r.feature}</td><td>${(r.applications||[]).join('<br>')}</td><td>${r.module.join('<br>')}</td><td>${r.requirements.join('<br>')}</td><td>${r.acceptance.covered}/${r.acceptance.total} (${r.acceptance.coverage}%)</td><td>${r.rules.join('<br>')}</td><td>${r.screens.join('<br>')}</td><td>${r.apis.join('<br>')}</td><td>${r.database.join('<br>')}</td><td>${r.permissions.join('<br>')}</td><td>${r.deepLinks.join('<br>')}</td><td>${r.tests.join('<br>')}</td><td>${(r.tasks||[]).join('<br>')}</td></tr>`).join('');
  fs.writeFileSync(path.join(site,'traceability.html'),shell('Typed Traceability',`<table><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr>${rowHtml}</table>`,'traceability.html'));
  const reqVerificationRows=(verification.requirements||[]).map(r=>`<tr><td>${escapeHtml(r.code)}</td><td>${escapeHtml(r.status)}</td><td>${r.acceptanceCovered}/${r.acceptanceTotal}</td><td>${r.acceptanceCoverage}%</td><td>${(r.acceptanceCriteria||[]).filter(x=>!x.covered).map(x=>escapeHtml(x.ref)).join('<br>')||'—'}</td></tr>`).join('');
  const ruleVerificationRows=(verification.businessRules||[]).map(r=>`<tr><td>${escapeHtml(r.code)}</td><td>${escapeHtml(r.criticality)}</td><td>${r.positiveCovered?'✓':'—'}</td><td>${r.negativeCovered?'✓':'—'}</td><td>${escapeHtml(r.tests.join(', ')||'—')}</td></tr>`).join('');
  const verificationHtml=`<div class="grid"><div class="card"><b>${verification.summary.acceptanceCovered||0}/${verification.summary.acceptanceCriteria||0}</b><br>Acceptance Criteria covered</div><div class="card"><b>${verification.summary.acceptanceCoverage??100}%</b><br>AC coverage</div><div class="card"><b>${verification.summary.criticalRulesFullyCovered||0}/${verification.summary.criticalBusinessRules||0}</b><br>Critical rules +/− covered</div><div class="card"><b>${(verification.summary.invalidAcceptanceRefs||0)+(verification.summary.invalidBusinessRuleCases||0)}</b><br>Invalid verification refs</div></div><h2>Requirement Acceptance Coverage</h2><table><tr><th>Requirement</th><th>Status</th><th>Covered</th><th>Coverage</th><th>Missing AC</th></tr>${reqVerificationRows||'<tr><td colspan="5">No Requirement entities yet.</td></tr>'}</table><h2>Business Rule Verification</h2><table><tr><th>Business Rule</th><th>Criticality</th><th>Positive</th><th>Negative</th><th>Tests</th></tr>${ruleVerificationRows||'<tr><td colspan="5">No Business Rule entities yet.</td></tr>'}</table>`;
  fs.writeFileSync(path.join(site,'verification.html'),shell('Acceptance & Verification',verificationHtml,'verification.html'));
  const specRows=(specification.features||[]).map(x=>`<tr><td>${escapeHtml(x.code)}</td><td>${escapeHtml(x.requestedLevel)}</td><td>${escapeHtml(x.effectiveLevel)}</td><td>${escapeHtml(x.targetMaturity)}</td><td>${escapeHtml(x.recommendedLevel)}</td><td>${escapeHtml(String(x.completeness))}%</td><td>${x.belowRecommended?'⚠':''}</td></tr>`).join('');
  const specHtml=`<div class="grid"><div class="card"><b>${specification.summary.lightweight||0}</b><br>Lightweight</div><div class="card"><b>${specification.summary.standard||0}</b><br>Standard</div><div class="card"><b>${specification.summary.full||0}</b><br>Full</div><div class="card"><b>${specification.summary.belowRecommended||0}</b><br>Below recommendation</div></div><table><tr><th>Feature</th><th>Requested</th><th>Effective</th><th>Maturity</th><th>Recommended</th><th>Completeness</th><th>Risk</th></tr>${specRows}</table>`;
  fs.writeFileSync(path.join(site,'specification.html'),shell('Progressive Specification',specHtml,'specification.html'));
  const govHtml=`<div class="grid"><div class="card"><b>${(governance.applications||[]).length}</b><br>Applications</div><div class="card"><b>${governance.requests.length}</b><br>Requests</div><div class="card"><b>${governance.workplans.length}</b><br>WorkPlans</div><div class="card"><b>${governance.tasks.length}</b><br>Tasks</div><div class="card"><b>${governance.bugs.length}</b><br>Bugs</div><div class="card"><b>${(governance.freshness||[]).filter(x=>x.status==='stale').length}</b><br>Stale docs</div><div class="card"><b>${governance.changesets.length}</b><br>ChangeSets</div><div class="card"><b>${governance.baselines.length}</b><br>Baselines</div></div><h2>Requests</h2>${governance.requests.map(x=>`<div class="card"><b>${escapeHtml(x.code)}</b> <span class="badge">${escapeHtml(x.status)}</span><br>${escapeHtml(x.title)}</div>`).join('')||'<p>No requests.</p>'}<h2>WorkPlans</h2>${governance.workplans.map(x=>`<div class="card"><b>${escapeHtml(x.id)}</b> <span class="badge">${escapeHtml(x.status)}</span><br>Feature: ${escapeHtml(x.featureCode)} · Spec: ${escapeHtml(x.specLevel||'n/a')} · Maturity: ${escapeHtml(x.targetMaturity||'n/a')} · ${escapeHtml(x.title)}</div>`).join('')||'<p>No WorkPlans.</p>'}<h2>Tasks</h2>${governance.tasks.map(x=>`<div class="card"><b>${escapeHtml(x.code)}</b> <span class="badge">${escapeHtml(x.status)}</span><br>${escapeHtml(x.title)}${x.workplanId?`<br><small>${escapeHtml(x.workplanId)}</small>`:''}</div>`).join('')||'<p>No tasks.</p>'}<h2>Freshness</h2>${(governance.freshness||[]).filter(x=>x.status!=='untracked').map(x=>`<div class="card"><b>${escapeHtml(x.code)}</b> <span class="badge">${escapeHtml(x.status)}</span><br>${escapeHtml(x.changedDependencies?.join(', ')||'No dependency drift')}</div>`).join('')||'<p>No reconciled freshness records yet.</p>'}<h2>ChangeSets</h2>${governance.changesets.map(x=>`<div class="card"><b>${escapeHtml(x.id)}</b> <span class="badge">${escapeHtml(String(x.summary?.count||0))} changes</span><br>${escapeHtml(x.reason||'')}</div>`).join('')||'<p>No ChangeSets.</p>'}<h2>Baselines</h2>${governance.baselines.map(x=>`<div class="card"><b>${escapeHtml(x.id)}</b><br>${escapeHtml(x.note||'')}</div>`).join('')||'<p>No baselines.</p>'}`; fs.writeFileSync(path.join(site,'governance.html'),shell('Implementation Governance',govHtml,'governance.html'));
  const nodes=graph.nodes; const w=1100,h=Math.max(500,Math.ceil(nodes.length/6)*140+100); const positions=new Map(nodes.map((n,i)=>[n.id,{x:100+(i%6)*180,y:80+Math.floor(i/6)*140}])); const edges=graph.edges.map(e=>{const a=positions.get(e.from),b=positions.get(e.to);return a&&b?`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#bbb"/><text x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2}" font-size="9">${escapeHtml(e.field)}</text>`:''}).join(''); const circles=nodes.map(n=>{const p=positions.get(n.id);return `<g><circle cx="${p.x}" cy="${p.y}" r="42" fill="#fff" stroke="#555"/><text x="${p.x}" y="${p.y-4}" text-anchor="middle" font-size="10">${escapeHtml(n.id.slice(0,18))}</text><text x="${p.x}" y="${p.y+11}" text-anchor="middle" font-size="9">${escapeHtml(n.type)}</text></g>`}).join('');
  fs.writeFileSync(path.join(site,'graph.html'),shell('Project Knowledge Graph',nodes.length?`<svg width="100%" viewBox="0 0 ${w} ${h}">${edges}${circles}</svg>`:'<p>No typed project entities yet. Import a pack or add project docs to populate the graph.','graph.html'));
  const diagramDocs=[];
  for(const p of markdownFiles()) { const text=fs.readFileSync(p,'utf8'); const parsed=parseFrontmatter(text); const title=parsed.data.title||rel(p); const page=slugPath(rel(p)); fs.writeFileSync(path.join(site,'pages',page),shell(title,`<p><small>${escapeHtml(rel(p))}</small></p>${renderMarkdown(parsed.body)}`,'','../')); if(text.includes('```mermaid'))diagramDocs.push({title,path:page}); }
  fs.writeFileSync(path.join(site,'flows.html'),shell('Diagram Gallery',diagramDocs.length?diagramDocs.map(d=>`<div class="card"><a href="pages/${d.path}">${escapeHtml(d.title)}</a></div>`).join(''):'<p>No Mermaid diagrams found yet. Flow templates and prompts describe how to add them.</p>','flows.html'));
  fs.writeFileSync(path.join(site,'search-index.json'),JSON.stringify(catalog.documents.map(d=>({title:d.title,path:`pages/${slugPath(d.path)}`,text:d.path})),null,2));
  console.log(`Built static site with ${catalog.documents.length} document pages.`);
}
function checkSite(){const site=workspaceAbs('site');let broken=[];for(const p of walk(site,x=>x.endsWith('.html'))){const text=fs.readFileSync(p,'utf8');for(const m of text.matchAll(/href="([^"]+)"/g)){const href=m[1];if(/^https?:|^mailto:|^#|^javascript:/.test(href))continue;const target=path.resolve(path.dirname(p),href.split('#')[0]);if(href&& !fs.existsSync(target))broken.push(`${rel(p)} -> ${href}`);}}console.log(`Site link check: ${broken.length} broken link(s)`);broken.forEach(x=>console.log('[BROKEN] '+x));return broken.length===0;}
function profileCheck(){const standards=resolveStandards(profile);let ok=true;for(const s of standards){if(!fs.existsSync(path.join(ROOT,s.path))){ok=false;console.log(`[MISSING] ${s.layer}: ${s.path}`);}}console.log(`Profile: ${(profile.projectTypes||[]).join(', ')||'(generic)'} / ${(profile.technologyStacks||[]).join(', ')||'(no stack selected)'}`);console.log(`Applicable standards: ${standards.length}`);standards.forEach(s=>console.log(`- ${s.layer}: ${s.path}`));return ok;}
function serve(){const site=workspaceAbs('site');const port=Number(process.env.PORT||4173);http.createServer((req,res)=>{let u=decodeURIComponent((req.url||'/').split('?')[0]);if(u==='/')u='/index.html';let p=path.resolve(site,'.'+u);if(!p.startsWith(site)){res.writeHead(403).end();return;}if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);res.end('Not found');return;}const ext=path.extname(p);const ct={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.json':'application/json'}[ext]||'application/octet-stream';res.writeHead(200,{'content-type':ct});fs.createReadStream(p).pipe(res);}).listen(port,'127.0.0.1',()=>console.log(`Docs site: http://127.0.0.1:${port}`));}

function clean(){fs.rmSync(workspaceAbs('site'),{recursive:true,force:true});fs.rmSync(path.join(ROOT,'docs/_generated'),{recursive:true,force:true});console.log(`Removed ${workspaceRel('site')}/ and docs/_generated/.`);}
function watch(){build();console.log('Watching documentation sources...');let timer=null;const roots=['docs','standards','prompts','workflows','templates','registry','sourceBases'];for(const key of roots){const abs=key==='docs'?path.join(ROOT,'docs'):workspaceAbs(key);if(!fs.existsSync(abs))continue;fs.watch(abs,{recursive:true},(event,filename)=>{if(!filename)return;clearTimeout(timer);timer=setTimeout(()=>{try{build();checkSite();console.log(`Rebuilt after ${key}/${filename}`);}catch(e){console.error('[WATCH ERROR] '+e.message);}},250);});}}

function help(){console.log('docs-tool commands: profile, validate, sync, build, check-site, serve, clean, watch');}
let ok=true;if(cmd==='profile')ok=profileCheck();else if(cmd==='validate')ok=validate();else if(cmd==='sync')sync();else if(cmd==='build')build();else if(cmd==='check-site')ok=checkSite();else if(cmd==='serve')serve();else if(cmd==='clean')clean();else if(cmd==='watch')watch();else help();if(!ok)process.exitCode=1;
