import fs from 'node:fs';
import path from 'node:path';
import { ROOT, parseArgs, loadJson, existingWorkspaceAbs } from '../lib/common.mjs';
import { sourceProfiles, sourceLock, saveSourceLock, applications, applicationByCode, profileById, loadBase, latestBaseVersion, validateAllBases, createApplicationEntity, copyTemplate, ensureProjectSelectors, checkApplication, listBaseVersions } from '../lib/source-workspace.mjs';
import { markBrownfieldAdoption } from '../lib/brownfield.mjs';

const action=process.argv[2]||'help'; const args=parseArgs(process.argv.slice(3));
const req=n=>{if(!args[n])throw new Error(`Missing --${n}`);return String(args[n]);};
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'app';
function safeRoot(rel){ const abs=path.resolve(ROOT,String(rel)); if(!(abs===ROOT||abs.startsWith(ROOT+path.sep))) throw new Error(`Source root must stay inside project workspace: ${rel}`); return abs; }
function recommendedVariant(p){ const project=loadJson('project.profile.json',{}); const level=project.documentation?.defaultSpecLevel||'standard'; const maturity=project.documentation?.targetMaturity||'production'; if(['concept','prototype'].includes(maturity)||level==='lightweight') return p.variants?.includes('minimal')?'minimal':p.defaultVariant; return p.variants?.includes('production')?'production':p.defaultVariant; }
function list(){ const cfg=sourceProfiles(); for(const [id,p] of Object.entries(cfg.profiles||{})) console.log(`${id}\t${p.applicationType}\t${p.technologyStack}\t${p.sourceBase||'(adopt-only)'}\t${p.defaultRoot}`); }
function validate(){ const errors=validateAllBases(); const baseRoot=existingWorkspaceAbs('sourceBases'); let bases=0,variants=0; if(fs.existsSync(baseRoot)) for(const e of fs.readdirSync(baseRoot,{withFileTypes:true})){ if(!e.isDirectory())continue; const version=latestBaseVersion(e.name); if(!version)continue; bases++; const loaded=loadBase(e.name,version); variants+=Object.keys(loaded.manifest.variants||{}).length; } console.log(`Source Base validation: ${errors.length} error(s); ${bases} base(s), ${variants} variant(s).`); errors.forEach(e=>console.log(`[ERROR] ${e}`)); if(errors.length)process.exitCode=1; }
function recommend(){ const cfg=sourceProfiles(); const type=args.type?String(args.type):null, stack=args.stack?String(args.stack):null; const matches=Object.entries(cfg.profiles||{}).filter(([,p])=>(!type||p.applicationType===type)&&(!stack||p.technologyStack===stack||p.sourceBase===stack)); if(!matches.length) throw new Error(`No source profile matches type=${type||'*'} stack=${stack||'*'}`); for(const [id,p] of matches) console.log(`${id}: root=${p.defaultRoot}, base=${p.sourceBase||'adopt-existing'}, recommendedVariant=${recommendedVariant(p)}`); }
function init(){ const code=req('code'),profileId=req('profile'); if(applicationByCode(code))throw new Error(`Application exists: ${code}`); const p=profileById(profileId); if(!p)throw new Error(`Unknown source profile: ${profileId}`); if(!p.sourceBase)throw new Error(`${profileId} has no bundled Source Base; use source:adopt or add a Source Base first.`); const baseId=String(args.base||p.sourceBase),version=String(args.version||latestBaseVersion(baseId)||''); const loaded=loadBase(baseId,version); const variant=String(args.variant||recommendedVariant(p)||p.defaultVariant||'production'),variantCfg=loaded.manifest.variants?.[variant]; if(!variantCfg)throw new Error(`Unknown variant ${variant} for ${baseId}@${loaded.version}`); const sourceRoot=String(args.root||p.defaultRoot),target=safeRoot(sourceRoot); const title=String(args.title||code); copyTemplate(path.join(loaded.dir,variantCfg.template),target,{'__APP_CODE__':code,'__APP_NAME__':title,'__PACKAGE_NAME__':slug(code)}); const entityPath=createApplicationEntity({code,title,profileId,sourceRoot,baseId,baseVersion:loaded.version,variant,origin:'source-base',owner:String(args.owner||'Engineering')}); const lock=sourceLock(); lock.applications=lock.applications||{}; lock.applications[code]={sourceRoot,sourceProfile:profileId,technologyStack:p.technologyStack,origin:'source-base',sourceBase:{id:baseId,version:loaded.version},variant,materializedAt:new Date().toISOString()}; saveSourceLock(lock); ensureProjectSelectors(p); console.log(`Initialized ${code} from ${baseId}@${loaded.version}/${variant} -> ${sourceRoot}`); console.log(`Application entity: ${entityPath}`); }
function adopt(){ const code=req('code'),profileId=req('profile'),sourceRoot=req('root'); if(applicationByCode(code))throw new Error(`Application exists: ${code}`); const p=profileById(profileId); if(!p)throw new Error(`Unknown source profile: ${profileId}`); const abs=safeRoot(sourceRoot); if(!fs.existsSync(abs))throw new Error(`Existing source root not found: ${sourceRoot}`); const title=String(args.title||code); const entityPath=createApplicationEntity({code,title,profileId,sourceRoot,origin:'existing',owner:String(args.owner||'Engineering')}); const lock=sourceLock(); lock.applications=lock.applications||{}; lock.applications[code]={sourceRoot,sourceProfile:profileId,technologyStack:p.technologyStack,origin:'existing',adoptedAt:new Date().toISOString()}; saveSourceLock(lock); ensureProjectSelectors(p); markBrownfieldAdoption({strategy:'adopt-in-place'}); console.log(`Adopted ${code} at ${sourceRoot} using ${profileId}`); console.log(`Application entity: ${entityPath}`); }
function check(){ const selected=args.app?[applicationByCode(String(args.app))]:applications(); if(args.app&&!selected[0])throw new Error(`Application not found: ${args.app}`); let errors=0,warnings=0; if(!selected.length){console.log('Source workspace: PASS (no application entities configured).');return;} for(const app of selected){const r=checkApplication(app);errors+=r.errors.length;warnings+=r.warnings.length;console.log(`${app.code}: ${r.errors.length?'FAIL':'PASS'} profile=${app.meta.source_profile} root=${app.meta.source_root}`);r.errors.forEach(x=>console.log(`  [ERROR] ${x}`));r.warnings.forEach(x=>console.log(`  [WARN] ${x}`));} console.log(`Source workspace check: ${errors} error(s), ${warnings} warning(s), ${selected.length} application(s).`); if(errors)process.exitCode=1; }
function status(){ const lock=sourceLock(); const apps=applications(); if(!apps.length){console.log('No application entities.');return;} for(const app of apps){const l=lock.applications?.[app.code];console.log(`${app.code}\t${app.meta.source_profile}\t${app.meta.source_root}\t${l?.origin||app.meta.source_origin||'unknown'}\t${l?.sourceBase?`${l.sourceBase.id}@${l.sourceBase.version}/${l.variant}`:'existing'}`);} }
function upgradeCheck(){ const code=req('app'),lock=sourceLock().applications?.[code]; if(!lock)throw new Error(`No source lock entry for ${code}`); if(!lock.sourceBase?.id){console.log(`${code}: adopted existing source; no Source Base upgrade lineage.`);return;} const versions=listBaseVersions(lock.sourceBase.id),latest=versions[versions.length-1]||lock.sourceBase.version; console.log(`${code}: current=${lock.sourceBase.id}@${lock.sourceBase.version}, latest=${latest}`); if(latest===lock.sourceBase.version)console.log('UP_TO_DATE'); else console.log('UPGRADE_AVAILABLE: create a reviewed migration WorkPlan; project source is never overwritten automatically.'); }
try{ if(action==='list')list(); else if(action==='validate')validate(); else if(action==='recommend')recommend(); else if(action==='init')init(); else if(action==='adopt')adopt(); else if(action==='check')check(); else if(action==='status')status(); else if(action==='upgrade-check')upgradeCheck(); else console.log('source-tool commands: list, validate, recommend [--type web|mobile|api] [--stack STACK], init --code APP-X --profile PROFILE [--variant minimal|production] [--root path], adopt --code APP-X --profile PROFILE --root path, check [--app APP-X], status, upgrade-check --app APP-X'); }
catch(e){console.error(`[ERROR] ${e.message}`);process.exitCode=1;}
