#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { loadConfig, projectRoot, scanDocuments, codeIndex, buildRelations, writeJson, ensureDir, posix } from './lib/core.mjs';

const config = await loadConfig();
const docs = await scanDocuments(config);
const entities = docs.filter((d) => d.isEntity);
const byCode = codeIndex(entities);
const duplicates = [...byCode.entries()].filter(([, v]) => v.length > 1);
const graph = buildRelations(docs, config);

if (duplicates.length || graph.broken.length) {
  console.error('Sync stopped because graph identity is invalid. Run npm run docs:validate for details.');
  process.exit(1);
}

const generatedDir = path.resolve(projectRoot, config.generatedDir);
const cacheDir = path.resolve(projectRoot, config.cacheDir);
await ensureDir(generatedDir);
await ensureDir(cacheDir);

const compactDocs = docs.map((d) => ({
  relPath: d.relPath,
  title: d.title,
  code: d.code,
  type: d.type,
  status: d.status,
  owner: d.owner,
  route: d.route,
  method: d.method,
  apiPath: d.apiPath,
  objectName: d.objectName,
  objectType: d.objectType,
  updatedAt: d.updatedAt,
  lastReviewedAt: d.lastReviewedAt,
  tags: d.tags,
  related: d.related,
  section: d.section,
  isEntity: d.isEntity,
  mermaidCount: d.mermaid.length,
  hash: d.hash
}));

const graphJson = {
  nodes: entities.map((d) => ({ id: d.code, label: d.title, type: d.type, status: d.status, path: d.relPath })),
  edges: graph.edges
};

await writeJson(path.join(cacheDir, 'catalog.json'), { generatedAt: new Date().toISOString(), documents: compactDocs });
await writeJson(path.join(cacheDir, 'graph.json'), graphJson);

function mdLink(d) {
  return `[${d.code || d.title}](../../${d.relPath})`;
}

const byType = new Map();
for (const d of entities) {
  if (!byType.has(d.type)) byType.set(d.type, []);
  byType.get(d.type).push(d);
}

let indexMd = '# Generated Document Index\n\n> Generated by `tools/scripts/sync-docs.mjs`. Do not edit manually.\n\n';
indexMd += `Generated: ${new Date().toISOString()}\n\n`;
for (const type of [...byType.keys()].sort()) {
  indexMd += `## ${type}\n\n| Code | Title | Status | Owner | Source |\n|---|---|---|---|---|\n`;
  for (const d of byType.get(type).sort((a, b) => a.code.localeCompare(b.code))) {
    indexMd += `| ${d.code} | ${d.title.replace(/\|/g, '\\|')} | ${d.status || ''} | ${d.owner || ''} | [open](../../${d.relPath}) |\n`;
  }
  indexMd += '\n';
}
await fs.writeFile(path.join(generatedDir, 'DOCUMENT_INDEX.md'), indexMd, 'utf8');

function neighbors(code, depth = 2) {
  const found = new Set([code]);
  let frontier = new Set([code]);
  for (let i = 0; i < depth; i++) {
    const next = new Set();
    for (const current of frontier) {
      for (const e of graph.edges) {
        if (e.from === current && !found.has(e.to)) next.add(e.to);
        if (e.to === current && !found.has(e.from)) next.add(e.from);
      }
    }
    for (const x of next) found.add(x);
    frontier = next;
  }
  found.delete(code);
  return [...found];
}

const featureDocs = entities.filter((d) => d.type === 'feature').sort((a, b) => a.code.localeCompare(b.code));
let traceMd = '# Generated Traceability Matrix\n\n> Generated from frontmatter `related` metadata. Do not edit manually.\n\n';
traceMd += '| Feature | Requirements | Rules | Screens | APIs | DB | Tests | Decisions |\n|---|---|---|---|---|---|---|---|\n';
const typesForColumn = {
  requirement: 'requirements',
  'business-rule': 'rules',
  screen: 'screens',
  api: 'apis',
  'database-object': 'db',
  'test-case': 'tests',
  'test-script': 'tests',
  decision: 'decisions'
};
for (const feature of featureDocs) {
  const groups = { requirements: [], rules: [], screens: [], apis: [], db: [], tests: [], decisions: [] };
  for (const code of neighbors(feature.code, 2)) {
    const d = byCode.get(code)?.[0];
    if (!d) continue;
    const col = typesForColumn[d.type];
    if (col) groups[col].push(d);
  }
  const cell = (arr) => arr.length ? arr.map((x) => `[${x.code}](../../${x.relPath})`).join('<br>') : '—';
  traceMd += `| [${feature.code}](../../${feature.relPath}) | ${cell(groups.requirements)} | ${cell(groups.rules)} | ${cell(groups.screens)} | ${cell(groups.apis)} | ${cell(groups.db)} | ${cell(groups.tests)} | ${cell(groups.decisions)} |\n`;
}
await fs.writeFile(path.join(generatedDir, 'TRACEABILITY_MATRIX.md'), traceMd, 'utf8');

const safeId = (code) => `N_${code.replace(/[^A-Za-z0-9_]/g, '_')}`;
const limited = entities.slice(0, 180);
const allowed = new Set(limited.map((x) => x.code));
let graphMd = '# Generated Project Graph\n\n> The static website also contains an interactive graph with pan/zoom and click-through navigation.\n\n```mermaid\nflowchart LR\n';
for (const d of limited) graphMd += `  ${safeId(d.code)}["${d.code}\\n${d.title.replaceAll('"', "'")}"]\n`;
for (const e of graph.edges.filter((e) => allowed.has(e.from) && allowed.has(e.to))) {
  graphMd += `  ${safeId(e.from)} -->|${e.relation}| ${safeId(e.to)}\n`;
}
graphMd += '```\n';
if (entities.length > limited.length) graphMd += `\n> Graph truncated to ${limited.length} nodes in Markdown. Use the web interactive graph for all ${entities.length} nodes.\n`;
await fs.writeFile(path.join(generatedDir, 'PROJECT_GRAPH.md'), graphMd, 'utf8');

const orphanEntities = entities.filter((d) => {
  if (d.type === 'module') return false;
  return !(graph.inbound.get(d.code)?.length) && !(graph.outbound.get(d.code)?.length);
});
const stale = entities.filter((d) => {
  if (!d.lastReviewedAt) return false;
  const t = Date.parse(`${d.lastReviewedAt}T00:00:00Z`);
  return Number.isFinite(t) && (Date.now() - t) / 86400000 > (config.maxReviewAgeDays || 180);
});
let healthMd = '# Generated Documentation Health\n\n';
healthMd += `- Entity documents: **${entities.length}**\n- Relations: **${graph.edges.length}**\n- Orphan entities: **${orphanEntities.length}**\n- Stale review: **${stale.length}**\n- Mermaid diagrams: **${docs.reduce((n, d) => n + d.mermaid.length, 0)}**\n\n`;
healthMd += '## Orphan Entities\n\n' + (orphanEntities.length ? orphanEntities.map((d) => `- [${d.code}](../../${d.relPath}) — ${d.title}`).join('\n') : '- None') + '\n\n';
healthMd += '## Stale Documents\n\n' + (stale.length ? stale.map((d) => `- [${d.code}](../../${d.relPath}) — reviewed ${d.lastReviewedAt}`).join('\n') : '- None') + '\n';
await fs.writeFile(path.join(generatedDir, 'DOCUMENT_HEALTH.md'), healthMd, 'utf8');

console.log(`Synced ${docs.length} markdown files and ${entities.length} entities.`);
console.log(`Generated: ${posix(path.relative(projectRoot, generatedDir))}/DOCUMENT_INDEX.md`);
console.log(`Generated: ${posix(path.relative(projectRoot, generatedDir))}/TRACEABILITY_MATRIX.md`);
console.log(`Generated: ${posix(path.relative(projectRoot, generatedDir))}/PROJECT_GRAPH.md`);
console.log(`Generated: ${posix(path.relative(projectRoot, generatedDir))}/DOCUMENT_HEALTH.md`);
console.log(`Cache: ${posix(path.relative(projectRoot, cacheDir))}/catalog.json + graph.json`);
