import fs from 'node:fs';
import path from 'node:path';
import {root, loadConfig, contentFiles, rel, parseFrontmatter, loadEntities, readJson, escapeHtml, slug} from './lib/core.mjs';
import {markdownToHtml} from './lib/markdown.mjs';
const cfg=loadConfig(), site=path.resolve(root,cfg.siteDir); fs.rmSync(site,{recursive:true,force:true}); fs.mkdirSync(path.join(site,'pages'),{recursive:true});fs.mkdirSync(path.join(site,'assets'),{recursive:true});
const entities=loadEntities(cfg), byFile=new Map(entities.map(e=>[e.file,e]));
const graph=readJson(`${cfg.generatedDir}/graph.json`,{nodes:[],edges:[]}), trace=readJson(`${cfg.generatedDir}/traceability.json`,[]), health=readJson(`${cfg.generatedDir}/health.json`,[]);
const projectTypes=readJson('registry/project-types.json',{projectTypes:{}}).projectTypes||{}, stacks=readJson('registry/technology-stacks.json',{technologyStacks:{}}).technologyStacks||{}, profile=readJson('project-profile.json',{projectName:'Starter Template',projectTypes:[],technologyStacks:[],implementationGate:{}});
const pages=[];
function pagePath(file){return 'pages/'+slug(file.replace(/\.md$/,''))+'.html';}
for(const p of contentFiles(cfg)){
 const file=rel(p), raw=fs.readFileSync(p,'utf8'), fm=parseFrontmatter(raw), body=fm.data?fm.body:raw, entity=byFile.get(file); const title=entity?.title||body.match(/^#\s+(.+)$/m)?.[1]||path.basename(file);
 pages.push({file,title,type:entity?.type||'document',code:entity?.code||'',page:pagePath(file),text:body.replace(/[`#*|>\[\]()_-]/g,' ').replace(/\s+/g,' ').slice(0,12000)});
 const html=layout(title,markdownToHtml(body),pages.length?file:''); fs.writeFileSync(path.join(site,pagePath(file)),html);
}
function nav(){return `<a href="../index.html">Dashboard</a><a href="../catalog.html">Catalog</a><a href="../standards.html">Standards</a><a href="../profile.html">Profile</a><a href="../traceability.html">Traceability</a><a href="../graph.html">Graph</a><a href="../flows.html">Diagrams</a>`;}
function layout(title,content,file=''){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><link rel="stylesheet" href="${file?'../':''}assets/style.css"></head><body><header><strong>Project Docs</strong><nav>${file?nav():nav().replaceAll('../','')}</nav><button id="theme">◐</button></header><main><div class="crumb">${escapeHtml(file)}</div>${content}</main><script src="${file?'../':''}assets/app.js"></script><script type="module" src="${file?'../':''}assets/mermaid-loader.js"></script></body></html>`;}
const css=`:root{--bg:#fff;--fg:#172033;--mut:#64748b;--card:#f8fafc;--line:#e2e8f0;--accent:#2563eb}html[data-theme=dark]{--bg:#0b1220;--fg:#e5edf8;--mut:#94a3b8;--card:#121c2d;--line:#253247;--accent:#60a5fa}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.65 Inter,system-ui,sans-serif}header{position:sticky;top:0;z-index:10;display:flex;gap:20px;align-items:center;padding:12px 24px;border-bottom:1px solid var(--line);background:var(--bg)}nav{display:flex;gap:14px;flex:1}a{color:var(--accent);text-decoration:none}main{max-width:1180px;margin:auto;padding:28px}h1,h2,h3{line-height:1.25;margin-top:1.5em}.crumb{color:var(--mut);font-size:12px}.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.card{border:1px solid var(--line);background:var(--card);padding:16px;border-radius:12px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{border:1px solid var(--line);padding:8px;text-align:left;vertical-align:top}pre{overflow:auto;padding:14px;background:var(--card);border:1px solid var(--line);border-radius:8px}code{font-family:ui-monospace,SFMono-Regular,monospace}.diagram-card{padding:12px;border:1px solid var(--line);border-radius:12px;margin:16px 0}.search{width:100%;padding:12px;border:1px solid var(--line);border-radius:8px;background:var(--bg);color:var(--fg)}.node{cursor:pointer}.muted{color:var(--mut)}button{background:var(--card);color:var(--fg);border:1px solid var(--line);border-radius:8px;padding:6px 10px}`;
fs.writeFileSync(path.join(site,'assets/style.css'),css);
fs.writeFileSync(path.join(site,'assets/app.js'),`document.getElementById('theme')?.addEventListener('click',()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme==='dark'?'light':'dark';localStorage.theme=d.dataset.theme});document.documentElement.dataset.theme=localStorage.theme||'light';`);
const localMermaid=path.resolve(root,'tools/vendor/mermaid.esm.min.mjs'); if(fs.existsSync(localMermaid)) fs.copyFileSync(localMermaid,path.join(site,'assets/mermaid.esm.min.mjs'));
fs.writeFileSync(path.join(site,'assets/mermaid-loader.js'),`const local='./mermaid.esm.min.mjs'; async function run(){try{let m;try{m=await import(local)}catch{m=await import('https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs')}m.default.initialize({startOnLoad:true,securityLevel:'loose',theme:'neutral'})}catch(e){console.warn('Mermaid unavailable; source remains visible.',e)}}run();`);
fs.writeFileSync(path.join(site,'search-index.json'),JSON.stringify(pages,null,2));
const stats={documents:pages.length,entities:entities.length,nodes:graph.nodes.length,edges:graph.edges.length,stale:health.length};
const cards=Object.entries(stats).map(([k,v])=>`<div class="card"><div class="muted">${k}</div><h2>${v}</h2></div>`).join('');
const dashboard=`<h1>Documentation Dashboard</h1><div class="card-grid">${cards}</div><h2>Search</h2><input class="search" id="q" placeholder="Search documentation..."><div id="results"></div><h2>Standards profiles</h2><p>Use <code>project-profile.json</code> to select web/mobile/api and technology-specific standards.</p><script>fetch('search-index.json').then(r=>r.json()).then(d=>{const q=document.getElementById('q'),o=document.getElementById('results');q.oninput=()=>{const x=q.value.toLowerCase().trim();o.innerHTML=x?d.filter(p=>(p.title+' '+p.code+' '+p.text).toLowerCase().includes(x)).slice(0,40).map(p=>'<p><a href="'+p.page+'">'+p.code+' '+p.title+'</a> <span class="muted">'+p.file+'</span></p>').join(''):''}})</script>`;
fs.writeFileSync(path.join(site,'index.html'),layout('Documentation Dashboard',dashboard));
const catRows=pages.map(p=>`<tr><td>${escapeHtml(p.code)}</td><td>${escapeHtml(p.type)}</td><td><a href="${p.page}">${escapeHtml(p.title)}</a></td><td>${escapeHtml(p.file)}</td></tr>`).join('');
fs.writeFileSync(path.join(site,'catalog.html'),layout('Catalog',`<h1>Catalog</h1><div class="table-wrap"><table><thead><tr><th>Code</th><th>Type</th><th>Title</th><th>File</th></tr></thead><tbody>${catRows}</tbody></table></div>`));
const std=[]; for(const t of profile.projectTypes||[]){const x=projectTypes[t];if(x)for(const f of x.requiredStandards)std.push({kind:'Project Type',profile:t,file:`${x.standardsRoot}/${f}`})} for(const st of profile.technologyStacks||[]){const x=stacks[st];if(x)for(const f of x.requiredStandards)std.push({kind:'Stack',profile:st,file:`${x.standardsRoot}/${f}`})}
const stdRows=std.map(x=>{const pg=pages.find(p=>p.file===x.file);return `<tr><td>${x.kind}</td><td>${x.profile}</td><td>${pg?`<a href="${pg.page}">${x.file}</a>`:x.file}</td></tr>`}).join('');
fs.writeFileSync(path.join(site,'standards.html'),layout('Applicable Standards',`<h1>Applicable Standards</h1><p>Derived from project profile.</p><table><thead><tr><th>Layer</th><th>Profile</th><th>Standard</th></tr></thead><tbody>${stdRows}</tbody></table>`));
const profileHtml=`<h1>Project Profile</h1><h2>${escapeHtml(profile.projectName||'Starter template')}</h2><h3>Project Types</h3><p>${(profile.projectTypes||[]).map(escapeHtml).join(', ')}</p><h3>Technology Stacks</h3><p>${(profile.technologyStacks||[]).map(escapeHtml).join(', ')}</p><h3>Implementation Gate</h3><pre>${escapeHtml(JSON.stringify(profile.implementationGate||{},null,2))}</pre><p>Change <code>project-profile.json</code> then run <code>npm run profile:check</code>.</p>`;
fs.writeFileSync(path.join(site,'profile.html'),layout('Project Profile',profileHtml));
const trRows=trace.map(r=>`<tr><td>${r.feature}</td><td>${r.requirements.join('<br>')}</td><td>${r.screens.join('<br>')}</td><td>${r.apis.join('<br>')}</td><td>${r.database_objects.join('<br>')}</td><td>${r.tests.join('<br>')}</td><td>${[...r.permissions,...r.deep_links,...r.sync_policies].join('<br>')}</td></tr>`).join('');
fs.writeFileSync(path.join(site,'traceability.html'),layout('Traceability',`<h1>Typed Traceability</h1><p>No untyped generic 2-hop traversal.</p><div class="table-wrap"><table><thead><tr><th>Feature</th><th>Requirements</th><th>Screens</th><th>APIs</th><th>DB</th><th>Tests</th><th>Mobile contracts</th></tr></thead><tbody>${trRows}</tbody></table></div>`));
// Diagram gallery
const diagrams=[]; for(const p of contentFiles(cfg)){const text=fs.readFileSync(p,'utf8');for(const m of text.matchAll(/```mermaid\s*\n([\s\S]*?)```/g))diagrams.push({file:rel(p),source:m[1].trim()});}
fs.writeFileSync(path.join(site,'flows.html'),layout('Diagram Gallery',`<h1>Diagram Gallery</h1><p>${diagrams.length} Mermaid diagram(s).</p>`+diagrams.map(d=>`<h3>${escapeHtml(d.file)}</h3><div class="diagram-card"><pre class="mermaid">${escapeHtml(d.source)}</pre><details><summary>Source</summary><pre>${escapeHtml(d.source)}</pre></details></div>`).join('')));
// Interactive graph, layered by type with draggable-ish pan via SVG native scroll; click opens source page.
const entityPage=Object.fromEntries(entities.map(e=>[e.code,pagePath(e.file)]));
const graphData={...graph,pages:entityPage};
const graphHtml=`<h1>Project Knowledge Graph</h1><p>Typed edges only. Click node to open its source document.</p><input id="gf" class="search" placeholder="Filter code/title/type"><div id="g" style="overflow:auto;border:1px solid var(--line);border-radius:12px;margin-top:12px"></div><script>const D=${JSON.stringify(graphData)};function render(){const f=document.getElementById('gf').value.toLowerCase();const nodes=D.nodes.filter(n=>!f||(n.code+' '+n.title+' '+n.type).toLowerCase().includes(f));const keep=new Set(nodes.map(n=>n.code));const types=[...new Set(nodes.map(n=>n.type))];const pos={};let maxY=0;types.forEach((t,xi)=>{nodes.filter(n=>n.type===t).forEach((n,yi)=>{pos[n.code]={x:30+xi*220,y:50+yi*78};maxY=Math.max(maxY,50+yi*78)})});let s='<svg width="'+Math.max(1000,types.length*220+100)+'" height="'+Math.max(500,maxY+120)+'">';for(const e of D.edges)if(keep.has(e.from)&&keep.has(e.to)){const a=pos[e.from],b=pos[e.to];s+='<line x1="'+(a.x+160)+'" y1="'+(a.y+22)+'" x2="'+b.x+'" y2="'+(b.y+22)+'" stroke="currentColor" opacity=".18"/><text x="'+((a.x+b.x)/2)+'" y="'+((a.y+b.y)/2)+'" font-size="9" fill="currentColor" opacity=".55">'+e.relationKey+'</text>'}for(const n of nodes){const p=pos[n.code];s+='<g class="node" onclick="location.href=\''+(D.pages[n.code]||'#')+'\'"><rect x="'+p.x+'" y="'+p.y+'" width="160" height="44" rx="7" fill="var(--card)" stroke="var(--line)"/><text x="'+(p.x+8)+'" y="'+(p.y+17)+'" font-size="11" fill="currentColor">'+n.code+'</text><text x="'+(p.x+8)+'" y="'+(p.y+33)+'" font-size="10" fill="currentColor" opacity=".65">'+String(n.title).slice(0,23)+'</text></g>'}s+='</svg>';document.getElementById('g').innerHTML=s}document.getElementById('gf').oninput=render;render();</script>`;
fs.writeFileSync(path.join(site,'graph.html'),layout('Project Graph',graphHtml));
console.log(`Built static site: ${pages.length} pages, ${diagrams.length} Mermaid diagrams, ${graph.nodes.length} graph nodes.`);
