import fs from 'node:fs';
import path from 'node:path';
import {root,loadEntities,loadConfig,parseFrontmatter} from './lib/core.mjs';
import {parseArgs,resolvePackDir,loadManifest,renderPack,loadPackLock,savePackLock,snapshotDir,projectRel,hash} from './lib/packs.mjs';
process.on('uncaughtException',e=>{console.error(`ERROR ${e.message}`);process.exit(1);});
process.on('unhandledRejection',e=>{console.error(`ERROR ${e?.message||e}`);process.exit(1);});
const args=parseArgs(process.argv.slice(2));const dir=resolvePackDir(args._[0]);const m=loadManifest(dir);const lock=loadPackLock();if(lock.imports?.[m.packageId])throw new Error(`${m.packageId} is already imported. Use pack:diff / pack:upgrade.`);
const pack=renderPack(dir,m,args);const projectIdx=new Map(loadEntities(loadConfig()).map(e=>[e.code,e]));const rows=[];let blocked=false;
for(const f of pack.rendered){const dest=path.resolve(root,f.projectPath);const exists=fs.existsSync(dest);const fm=parseFrontmatter(f.content).data;const collision=projectIdx.get(f.projectCode);let action=exists?'overwrite':'create';if(collision&&collision.file!==f.projectPath){action='code-collision';blocked=true;}if(exists&&fs.readFileSync(dest,'utf8')!==f.content){action='file-conflict';blocked=true;}rows.push({code:f.projectCode,path:f.projectPath,action,source:f.path,title:fm?.title||''});}
console.log(`# Import preview: ${m.packageId}@${m.version}`);console.log(`Features: ${pack.features.join(', ')}`);console.log(`Target: ${pack.targetRoot}`);for(const r of rows)console.log(`${r.action.padEnd(14)} ${r.code} -> ${r.path}`);const reviewPending=pack.reviewRequired.filter(k=>!pack.explicit.includes(k));if(reviewPending.length)console.log(`Review-required defaults: ${reviewPending.join(', ')}`);const activeDeps=(m.dependencies||[]).filter(d=>!d.whenFeature||pack.features.includes(d.whenFeature));if(activeDeps.length){console.log('Dependencies to review:');for(const d of activeDeps)console.log(`  - ${d.kind||'dependency'}: ${d.name||d.packageId||''}${d.whenFeature?` (feature ${d.whenFeature})`:''}`);}
if(!args.apply){console.log('Preview only. Re-run with --apply after review.');process.exit(blocked?2:0);}if(blocked)throw new Error('Import blocked by file/code conflict. Choose another --target-root or --namespace.');
for(const f of pack.rendered){const dest=path.resolve(root,f.projectPath);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,f.content);}
const snapBase=snapshotDir(m.packageId,m.version);fs.rmSync(snapBase,{recursive:true,force:true});const fileMap=[];for(const f of pack.rendered){const sp=path.join(snapBase,f.path);fs.mkdirSync(path.dirname(sp),{recursive:true});fs.writeFileSync(sp,f.content);fileMap.push({sourcePath:f.path,projectPath:f.projectPath,entityCode:f.projectCode,originalEntityCode:f.entityCode,snapshotPath:projectRel(sp),baseHash:hash(f.content)});}
lock.imports=lock.imports||{};lock.imports[m.packageId]={packageId:m.packageId,version:m.version,starterSchemaRange:m.starterSchemaRange,source:projectRel(dir),importedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),enabledFeatures:pack.features,variables:pack.variables,namespace:pack.namespace,targetRoot:pack.targetRoot,codeMap:pack.codeMap,fileMap,upgradePolicy:m.upgradePolicy,reviewStatus:args.acceptDefaults?'approved':'pending',reviewRequiredDefaults:reviewPending,dependencies:activeDeps,reviewNotes:m.reviewNotes||[],reviewHistory:args.acceptDefaults?[{at:new Date().toISOString(),action:'approved-at-import',note:'--accept-defaults'}]:[]};savePackLock(lock);console.log(`Imported ${pack.rendered.length} file(s). Pack review status: ${lock.imports[m.packageId].reviewStatus}.`);
