import fs from 'node:fs';
import path from 'node:path';
import {root} from './lib/core.mjs';
import {parseArgs,proposalRoot,timestamp,savePackLock,snapshotDir,projectRel,hash} from './lib/packs.mjs';
import {calculatePackDiff} from './lib/pack-diff.mjs';
process.on('uncaughtException',e=>{console.error(`ERROR ${e.message}`);process.exit(1);});
process.on('unhandledRejection',e=>{console.error(`ERROR ${e?.message||e}`);process.exit(1);});
const a=parseArgs(process.argv.slice(2));const id=a._[0];if(!id)throw new Error('Usage: pack:upgrade -- <packageId> --source <packDir> [--apply] [--accept-local-merge]');const d=calculatePackDiff(id,a.source||`../reusable-modules/${id}`,a);const stamp=timestamp(),proposal=path.join(proposalRoot,id,`${d.old.version}-to-${d.manifest.version}-${stamp}`);fs.mkdirSync(path.join(proposal,'upstream'),{recursive:true});
for(const r of d.rows)if(r.upstream?.content){const p=path.join(proposal,'upstream',r.sourcePath);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,r.upstream.content);}
const report={packageId:id,fromVersion:d.old.version,toVersion:d.manifest.version,generatedAt:new Date().toISOString(),rows:d.rows.map(({upstream,...x})=>x),conflictCount:d.conflicts.length,manualReviewCount:d.reviewRequired.length};fs.writeFileSync(path.join(proposal,'report.json'),JSON.stringify(report,null,2)+'\n');let md=`# Capability Pack Upgrade Proposal\n\n- Package: ${id}\n- From: ${d.old.version}\n- To: ${d.manifest.version}\n- Conflicts: ${d.conflicts.length}\n- Manual review deletions: ${d.reviewRequired.length}\n\n| Status | Entity | Project file | Source |\n|---|---|---|---|\n`;for(const r of d.rows)md+=`| ${r.status} | ${r.entityCode||''} | ${r.projectPath||''} | ${r.sourcePath} |\n`;fs.writeFileSync(path.join(proposal,'REPORT.md'),md);console.log(`Proposal: ${projectRel(proposal)}`);
if(!a.apply){console.log('No project files changed. Review proposal, then re-run with --apply.');process.exit(d.conflicts.length?2:0);}if(d.reviewRequired.length)throw new Error('Upgrade includes upstream deletions. Resolve manually before applying.');if(d.conflicts.length&&!a.acceptLocalMerge)throw new Error('Conflicts exist. Resolve local files, then use --accept-local-merge only after reviewing the merged result.');
for(const r of d.rows){if(!r.upstream)continue;if(['upstream-only','added'].includes(r.status)){const p=path.resolve(root,r.projectPath);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,r.upstream.content);}else if(r.status==='added-collision')throw new Error(`Cannot apply added collision: ${r.projectPath}`);}
const snapBase=snapshotDir(id,d.manifest.version);fs.rmSync(snapBase,{recursive:true,force:true});const fileMap=[];for(const f of d.upstream.rendered){const sp=path.join(snapBase,f.path);fs.mkdirSync(path.dirname(sp),{recursive:true});fs.writeFileSync(sp,f.content);const oldMap=(d.old.fileMap||[]).find(x=>x.sourcePath===f.path);fileMap.push({sourcePath:f.path,projectPath:oldMap?.projectPath||f.projectPath,entityCode:f.projectCode,originalEntityCode:f.entityCode,snapshotPath:projectRel(sp),baseHash:hash(f.content)});}
const entry={...d.old,version:d.manifest.version,starterSchemaRange:d.manifest.starterSchemaRange,updatedAt:new Date().toISOString(),variables:d.upstream.variables,enabledFeatures:d.upstream.features,codeMap:d.upstream.codeMap,fileMap,upgradePolicy:d.manifest.upgradePolicy,reviewStatus:'pending',reviewNotes:d.manifest.reviewNotes||[],reviewHistory:[...(d.old.reviewHistory||[]),{at:new Date().toISOString(),action:'upgrade-applied',from:d.old.version,to:d.manifest.version}]};d.lock.imports[id]=entry;savePackLock(d.lock);console.log(`Applied safe upstream changes and updated pack lock to ${d.manifest.version}. Review status is pending; run validation and project review.`);
